/** Generated by YAKINDU Statechart Tools code generator. */
package fr.univcotedazur.polytech.si4.fsm.project.mvp;

import fr.univcotedazur.polytech.si4.fsm.project.ITimer;
import java.util.LinkedList;
import java.util.List;
import java.util.Queue;
import java.util.concurrent.BlockingQueue;
import java.util.concurrent.LinkedBlockingQueue;

public class MVPStatemachine implements IMVPStatemachine {
	protected class SCInterfaceImpl implements SCInterface {
	
		private List<SCInterfaceListener> listeners = new LinkedList<SCInterfaceListener>();
		
		public List<SCInterfaceListener> getListeners() {
			return listeners;
		}
		private boolean optionButton;
		
		
		public void raiseOptionButton() {
			synchronized(MVPStatemachine.this) {
				inEventQueue.add(
					new Runnable() {
						@Override
						public void run() {
							optionButton = true;
							singleCycle();
						}
					}
				);
				runCycle();
			}
		}
		
		private boolean podPlacement;
		
		
		public void raisePodPlacement() {
			synchronized(MVPStatemachine.this) {
				inEventQueue.add(
					new Runnable() {
						@Override
						public void run() {
							podPlacement = true;
							singleCycle();
						}
					}
				);
				runCycle();
			}
		}
		
		private boolean coffeeButton;
		
		
		public void raiseCoffeeButton() {
			synchronized(MVPStatemachine.this) {
				inEventQueue.add(
					new Runnable() {
						@Override
						public void run() {
							coffeeButton = true;
							singleCycle();
						}
					}
				);
				runCycle();
			}
		}
		
		private boolean teaButton;
		
		
		public void raiseTeaButton() {
			synchronized(MVPStatemachine.this) {
				inEventQueue.add(
					new Runnable() {
						@Override
						public void run() {
							teaButton = true;
							singleCycle();
						}
					}
				);
				runCycle();
			}
		}
		
		private boolean expressoButton;
		
		
		public void raiseExpressoButton() {
			synchronized(MVPStatemachine.this) {
				inEventQueue.add(
					new Runnable() {
						@Override
						public void run() {
							expressoButton = true;
							singleCycle();
						}
					}
				);
				runCycle();
			}
		}
		
		private boolean cancelButton;
		
		
		public void raiseCancelButton() {
			synchronized(MVPStatemachine.this) {
				inEventQueue.add(
					new Runnable() {
						@Override
						public void run() {
							cancelButton = true;
							singleCycle();
						}
					}
				);
				runCycle();
			}
		}
		
		private boolean insertCoin10;
		
		
		public void raiseInsertCoin10() {
			synchronized(MVPStatemachine.this) {
				inEventQueue.add(
					new Runnable() {
						@Override
						public void run() {
							insertCoin10 = true;
							singleCycle();
						}
					}
				);
				runCycle();
			}
		}
		
		private boolean insertCoin25;
		
		
		public void raiseInsertCoin25() {
			synchronized(MVPStatemachine.this) {
				inEventQueue.add(
					new Runnable() {
						@Override
						public void run() {
							insertCoin25 = true;
							singleCycle();
						}
					}
				);
				runCycle();
			}
		}
		
		private boolean insertCoin50;
		
		
		public void raiseInsertCoin50() {
			synchronized(MVPStatemachine.this) {
				inEventQueue.add(
					new Runnable() {
						@Override
						public void run() {
							insertCoin50 = true;
							singleCycle();
						}
					}
				);
				runCycle();
			}
		}
		
		private boolean nFC;
		
		
		public void raiseNFC() {
			synchronized(MVPStatemachine.this) {
				inEventQueue.add(
					new Runnable() {
						@Override
						public void run() {
							nFC = true;
							singleCycle();
						}
					}
				);
				runCycle();
			}
		}
		
		private boolean enoughMoneyInserted;
		
		
		public void raiseEnoughMoneyInserted() {
			synchronized(MVPStatemachine.this) {
				inEventQueue.add(
					new Runnable() {
						@Override
						public void run() {
							enoughMoneyInserted = true;
							singleCycle();
						}
					}
				);
				runCycle();
			}
		}
		
		private boolean cupPickedUp;
		
		
		public void raiseCupPickedUp() {
			synchronized(MVPStatemachine.this) {
				inEventQueue.add(
					new Runnable() {
						@Override
						public void run() {
							cupPickedUp = true;
							singleCycle();
						}
					}
				);
				runCycle();
			}
		}
		
		private boolean positionnerDosette;
		
		
		public void raisePositionnerDosette() {
			synchronized(MVPStatemachine.this) {
				inEventQueue.add(
					new Runnable() {
						@Override
						public void run() {
							positionnerDosette = true;
							singleCycle();
						}
					}
				);
				runCycle();
			}
		}
		
		private boolean seedGrind;
		
		
		public void raiseSeedGrind() {
			synchronized(MVPStatemachine.this) {
				inEventQueue.add(
					new Runnable() {
						@Override
						public void run() {
							seedGrind = true;
							singleCycle();
						}
					}
				);
				runCycle();
			}
		}
		
		private boolean bagPlacement;
		
		
		public void raiseBagPlacement() {
			synchronized(MVPStatemachine.this) {
				inEventQueue.add(
					new Runnable() {
						@Override
						public void run() {
							bagPlacement = true;
							singleCycle();
						}
					}
				);
				runCycle();
			}
		}
		
		private boolean waitingForWater;
		
		
		public void raiseWaitingForWater() {
			synchronized(MVPStatemachine.this) {
				inEventQueue.add(
					new Runnable() {
						@Override
						public void run() {
							waitingForWater = true;
							singleCycle();
						}
					}
				);
				runCycle();
			}
		}
		
		private boolean endWaterHeat;
		
		
		public void raiseEndWaterHeat() {
			synchronized(MVPStatemachine.this) {
				inEventQueue.add(
					new Runnable() {
						@Override
						public void run() {
							endWaterHeat = true;
							singleCycle();
						}
					}
				);
				runCycle();
			}
		}
		
		private boolean endFirstStep;
		
		
		public void raiseEndFirstStep() {
			synchronized(MVPStatemachine.this) {
				inEventQueue.add(
					new Runnable() {
						@Override
						public void run() {
							endFirstStep = true;
							singleCycle();
						}
					}
				);
				runCycle();
			}
		}
		
		private boolean endSecondStep;
		
		
		public void raiseEndSecondStep() {
			synchronized(MVPStatemachine.this) {
				inEventQueue.add(
					new Runnable() {
						@Override
						public void run() {
							endSecondStep = true;
							singleCycle();
						}
					}
				);
				runCycle();
			}
		}
		
		private boolean step2Expresso;
		
		
		public void raiseStep2Expresso() {
			synchronized(MVPStatemachine.this) {
				inEventQueue.add(
					new Runnable() {
						@Override
						public void run() {
							step2Expresso = true;
							singleCycle();
						}
					}
				);
				runCycle();
			}
		}
		
		private boolean endPackSeed;
		
		
		public void raiseEndPackSeed() {
			synchronized(MVPStatemachine.this) {
				inEventQueue.add(
					new Runnable() {
						@Override
						public void run() {
							endPackSeed = true;
							singleCycle();
						}
					}
				);
				runCycle();
			}
		}
		
		private boolean waterHeated;
		
		
		public void raiseWaterHeated() {
			synchronized(MVPStatemachine.this) {
				inEventQueue.add(
					new Runnable() {
						@Override
						public void run() {
							waterHeated = true;
							singleCycle();
						}
					}
				);
				runCycle();
			}
		}
		
		private boolean waitForCup;
		
		
		public void raiseWaitForCup() {
			synchronized(MVPStatemachine.this) {
				inEventQueue.add(
					new Runnable() {
						@Override
						public void run() {
							waitForCup = true;
							singleCycle();
						}
					}
				);
				runCycle();
			}
		}
		
		private boolean cupIsPlaced;
		
		
		public void raiseCupIsPlaced() {
			synchronized(MVPStatemachine.this) {
				inEventQueue.add(
					new Runnable() {
						@Override
						public void run() {
							cupIsPlaced = true;
							singleCycle();
						}
					}
				);
				runCycle();
			}
		}
		
		private boolean giveCup;
		
		
		public void raiseGiveCup() {
			synchronized(MVPStatemachine.this) {
				inEventQueue.add(
					new Runnable() {
						@Override
						public void run() {
							giveCup = true;
							singleCycle();
						}
					}
				);
				runCycle();
			}
		}
		
		private boolean cupIsTaken;
		
		
		public void raiseCupIsTaken() {
			synchronized(MVPStatemachine.this) {
				inEventQueue.add(
					new Runnable() {
						@Override
						public void run() {
							cupIsTaken = true;
							singleCycle();
						}
					}
				);
				runCycle();
			}
		}
		
		private boolean letInfuse;
		
		
		public void raiseLetInfuse() {
			synchronized(MVPStatemachine.this) {
				inEventQueue.add(
					new Runnable() {
						@Override
						public void run() {
							letInfuse = true;
							singleCycle();
						}
					}
				);
				runCycle();
			}
		}
		
		private boolean milkButton;
		
		
		public void raiseMilkButton() {
			synchronized(MVPStatemachine.this) {
				inEventQueue.add(
					new Runnable() {
						@Override
						public void run() {
							milkButton = true;
							singleCycle();
						}
					}
				);
				runCycle();
			}
		}
		
		private boolean syrupButton;
		
		
		public void raiseSyrupButton() {
			synchronized(MVPStatemachine.this) {
				inEventQueue.add(
					new Runnable() {
						@Override
						public void run() {
							syrupButton = true;
							singleCycle();
						}
					}
				);
				runCycle();
			}
		}
		
		private boolean crustButton;
		
		
		public void raiseCrustButton() {
			synchronized(MVPStatemachine.this) {
				inEventQueue.add(
					new Runnable() {
						@Override
						public void run() {
							crustButton = true;
							singleCycle();
						}
					}
				);
				runCycle();
			}
		}
		
		private boolean vanillaButton;
		
		
		public void raiseVanillaButton() {
			synchronized(MVPStatemachine.this) {
				inEventQueue.add(
					new Runnable() {
						@Override
						public void run() {
							vanillaButton = true;
							singleCycle();
						}
					}
				);
				runCycle();
			}
		}
		
		private boolean waterPoured;
		
		
		public void raiseWaterPoured() {
			synchronized(MVPStatemachine.this) {
				inEventQueue.add(
					new Runnable() {
						@Override
						public void run() {
							waterPoured = true;
							singleCycle();
						}
					}
				);
				runCycle();
			}
		}
		
		private boolean sugarAdded;
		
		
		public void raiseSugarAdded() {
			synchronized(MVPStatemachine.this) {
				inEventQueue.add(
					new Runnable() {
						@Override
						public void run() {
							sugarAdded = true;
							singleCycle();
						}
					}
				);
				runCycle();
			}
		}
		
		private boolean syrupAdded;
		
		
		public void raiseSyrupAdded() {
			synchronized(MVPStatemachine.this) {
				inEventQueue.add(
					new Runnable() {
						@Override
						public void run() {
							syrupAdded = true;
							singleCycle();
						}
					}
				);
				runCycle();
			}
		}
		
		private boolean step1ElementPlaced;
		
		
		public void raiseStep1ElementPlaced() {
			synchronized(MVPStatemachine.this) {
				inEventQueue.add(
					new Runnable() {
						@Override
						public void run() {
							step1ElementPlaced = true;
							singleCycle();
						}
					}
				);
				runCycle();
			}
		}
		
		private boolean noMilkOption;
		
		
		public void raiseNoMilkOption() {
			synchronized(MVPStatemachine.this) {
				inEventQueue.add(
					new Runnable() {
						@Override
						public void run() {
							noMilkOption = true;
							singleCycle();
						}
					}
				);
				runCycle();
			}
		}
		
		private boolean milkOption;
		
		
		public void raiseMilkOption() {
			synchronized(MVPStatemachine.this) {
				inEventQueue.add(
					new Runnable() {
						@Override
						public void run() {
							milkOption = true;
							singleCycle();
						}
					}
				);
				runCycle();
			}
		}
		
		private boolean milkAdded;
		
		
		public void raiseMilkAdded() {
			synchronized(MVPStatemachine.this) {
				inEventQueue.add(
					new Runnable() {
						@Override
						public void run() {
							milkAdded = true;
							singleCycle();
						}
					}
				);
				runCycle();
			}
		}
		
		private boolean sugar;
		
		
		public void raiseSugar() {
			synchronized(MVPStatemachine.this) {
				inEventQueue.add(
					new Runnable() {
						@Override
						public void run() {
							sugar = true;
							singleCycle();
						}
					}
				);
				runCycle();
			}
		}
		
		private boolean syrup;
		
		
		public void raiseSyrup() {
			synchronized(MVPStatemachine.this) {
				inEventQueue.add(
					new Runnable() {
						@Override
						public void run() {
							syrup = true;
							singleCycle();
						}
					}
				);
				runCycle();
			}
		}
		
		private boolean vanillaChosed;
		
		
		public boolean isRaisedVanillaChosed() {
			synchronized(MVPStatemachine.this) {
				return vanillaChosed;
			}
		}
		
		protected void raiseVanillaChosed() {
			synchronized(MVPStatemachine.this) {
				vanillaChosed = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onVanillaChosedRaised();
				}
			}
		}
		
		private boolean syrupChosed;
		
		
		public boolean isRaisedSyrupChosed() {
			synchronized(MVPStatemachine.this) {
				return syrupChosed;
			}
		}
		
		protected void raiseSyrupChosed() {
			synchronized(MVPStatemachine.this) {
				syrupChosed = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onSyrupChosedRaised();
				}
			}
		}
		
		private boolean crustChosed;
		
		
		public boolean isRaisedCrustChosed() {
			synchronized(MVPStatemachine.this) {
				return crustChosed;
			}
		}
		
		protected void raiseCrustChosed() {
			synchronized(MVPStatemachine.this) {
				crustChosed = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onCrustChosedRaised();
				}
			}
		}
		
		private boolean beginWaterHeat;
		
		
		public boolean isRaisedBeginWaterHeat() {
			synchronized(MVPStatemachine.this) {
				return beginWaterHeat;
			}
		}
		
		protected void raiseBeginWaterHeat() {
			synchronized(MVPStatemachine.this) {
				beginWaterHeat = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onBeginWaterHeatRaised();
				}
			}
		}
		
		private boolean milkChosed;
		
		
		public boolean isRaisedMilkChosed() {
			synchronized(MVPStatemachine.this) {
				return milkChosed;
			}
		}
		
		protected void raiseMilkChosed() {
			synchronized(MVPStatemachine.this) {
				milkChosed = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onMilkChosedRaised();
				}
			}
		}
		
		private boolean disableMissingIngredients;
		
		
		public boolean isRaisedDisableMissingIngredients() {
			synchronized(MVPStatemachine.this) {
				return disableMissingIngredients;
			}
		}
		
		protected void raiseDisableMissingIngredients() {
			synchronized(MVPStatemachine.this) {
				disableMissingIngredients = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onDisableMissingIngredientsRaised();
				}
			}
		}
		
		private boolean beginMachineCleaning;
		
		
		public boolean isRaisedBeginMachineCleaning() {
			synchronized(MVPStatemachine.this) {
				return beginMachineCleaning;
			}
		}
		
		protected void raiseBeginMachineCleaning() {
			synchronized(MVPStatemachine.this) {
				beginMachineCleaning = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onBeginMachineCleaningRaised();
				}
			}
		}
		
		private boolean addSugar;
		
		
		public boolean isRaisedAddSugar() {
			synchronized(MVPStatemachine.this) {
				return addSugar;
			}
		}
		
		protected void raiseAddSugar() {
			synchronized(MVPStatemachine.this) {
				addSugar = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onAddSugarRaised();
				}
			}
		}
		
		private boolean seedPacking;
		
		
		public boolean isRaisedSeedPacking() {
			synchronized(MVPStatemachine.this) {
				return seedPacking;
			}
		}
		
		protected void raiseSeedPacking() {
			synchronized(MVPStatemachine.this) {
				seedPacking = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onSeedPackingRaised();
				}
			}
		}
		
		private boolean cupPlacing;
		
		
		public boolean isRaisedCupPlacing() {
			synchronized(MVPStatemachine.this) {
				return cupPlacing;
			}
		}
		
		protected void raiseCupPlacing() {
			synchronized(MVPStatemachine.this) {
				cupPlacing = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onCupPlacingRaised();
				}
			}
		}
		
		private boolean bagPlacing;
		
		
		public boolean isRaisedBagPlacing() {
			synchronized(MVPStatemachine.this) {
				return bagPlacing;
			}
		}
		
		protected void raiseBagPlacing() {
			synchronized(MVPStatemachine.this) {
				bagPlacing = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onBagPlacingRaised();
				}
			}
		}
		
		private boolean seedGrinding;
		
		
		public boolean isRaisedSeedGrinding() {
			synchronized(MVPStatemachine.this) {
				return seedGrinding;
			}
		}
		
		protected void raiseSeedGrinding() {
			synchronized(MVPStatemachine.this) {
				seedGrinding = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onSeedGrindingRaised();
				}
			}
		}
		
		private boolean podPlacing;
		
		
		public boolean isRaisedPodPlacing() {
			synchronized(MVPStatemachine.this) {
				return podPlacing;
			}
		}
		
		protected void raisePodPlacing() {
			synchronized(MVPStatemachine.this) {
				podPlacing = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onPodPlacingRaised();
				}
			}
		}
		
		private boolean waitForWaterPoured;
		
		
		public boolean isRaisedWaitForWaterPoured() {
			synchronized(MVPStatemachine.this) {
				return waitForWaterPoured;
			}
		}
		
		protected void raiseWaitForWaterPoured() {
			synchronized(MVPStatemachine.this) {
				waitForWaterPoured = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onWaitForWaterPouredRaised();
				}
			}
		}
		
		private boolean waitForWaterHeated;
		
		
		public boolean isRaisedWaitForWaterHeated() {
			synchronized(MVPStatemachine.this) {
				return waitForWaterHeated;
			}
		}
		
		protected void raiseWaitForWaterHeated() {
			synchronized(MVPStatemachine.this) {
				waitForWaterHeated = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onWaitForWaterHeatedRaised();
				}
			}
		}
		
		private boolean coffeeChosed;
		
		
		public boolean isRaisedCoffeeChosed() {
			synchronized(MVPStatemachine.this) {
				return coffeeChosed;
			}
		}
		
		protected void raiseCoffeeChosed() {
			synchronized(MVPStatemachine.this) {
				coffeeChosed = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onCoffeeChosedRaised();
				}
			}
		}
		
		private boolean teaChosed;
		
		
		public boolean isRaisedTeaChosed() {
			synchronized(MVPStatemachine.this) {
				return teaChosed;
			}
		}
		
		protected void raiseTeaChosed() {
			synchronized(MVPStatemachine.this) {
				teaChosed = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onTeaChosedRaised();
				}
			}
		}
		
		private boolean expressoChosed;
		
		
		public boolean isRaisedExpressoChosed() {
			synchronized(MVPStatemachine.this) {
				return expressoChosed;
			}
		}
		
		protected void raiseExpressoChosed() {
			synchronized(MVPStatemachine.this) {
				expressoChosed = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onExpressoChosedRaised();
				}
			}
		}
		
		private boolean coin10Inserted;
		
		
		public boolean isRaisedCoin10Inserted() {
			synchronized(MVPStatemachine.this) {
				return coin10Inserted;
			}
		}
		
		protected void raiseCoin10Inserted() {
			synchronized(MVPStatemachine.this) {
				coin10Inserted = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onCoin10InsertedRaised();
				}
			}
		}
		
		private boolean coin25Inserted;
		
		
		public boolean isRaisedCoin25Inserted() {
			synchronized(MVPStatemachine.this) {
				return coin25Inserted;
			}
		}
		
		protected void raiseCoin25Inserted() {
			synchronized(MVPStatemachine.this) {
				coin25Inserted = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onCoin25InsertedRaised();
				}
			}
		}
		
		private boolean coin50Inserted;
		
		
		public boolean isRaisedCoin50Inserted() {
			synchronized(MVPStatemachine.this) {
				return coin50Inserted;
			}
		}
		
		protected void raiseCoin50Inserted() {
			synchronized(MVPStatemachine.this) {
				coin50Inserted = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onCoin50InsertedRaised();
				}
			}
		}
		
		private boolean cancel;
		
		
		public boolean isRaisedCancel() {
			synchronized(MVPStatemachine.this) {
				return cancel;
			}
		}
		
		protected void raiseCancel() {
			synchronized(MVPStatemachine.this) {
				cancel = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onCancelRaised();
				}
			}
		}
		
		private boolean nFCPayment;
		
		
		public boolean isRaisedNFCPayment() {
			synchronized(MVPStatemachine.this) {
				return nFCPayment;
			}
		}
		
		protected void raiseNFCPayment() {
			synchronized(MVPStatemachine.this) {
				nFCPayment = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onNFCPaymentRaised();
				}
			}
		}
		
		private boolean doTransaction;
		
		
		public boolean isRaisedDoTransaction() {
			synchronized(MVPStatemachine.this) {
				return doTransaction;
			}
		}
		
		protected void raiseDoTransaction() {
			synchronized(MVPStatemachine.this) {
				doTransaction = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onDoTransactionRaised();
				}
			}
		}
		
		private boolean endThirdStep;
		
		
		public boolean isRaisedEndThirdStep() {
			synchronized(MVPStatemachine.this) {
				return endThirdStep;
			}
		}
		
		protected void raiseEndThirdStep() {
			synchronized(MVPStatemachine.this) {
				endThirdStep = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onEndThirdStepRaised();
				}
			}
		}
		
		private boolean beginSecondStep;
		
		
		public boolean isRaisedBeginSecondStep() {
			synchronized(MVPStatemachine.this) {
				return beginSecondStep;
			}
		}
		
		protected void raiseBeginSecondStep() {
			synchronized(MVPStatemachine.this) {
				beginSecondStep = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onBeginSecondStepRaised();
				}
			}
		}
		
		private boolean pourMilk;
		
		
		public boolean isRaisedPourMilk() {
			synchronized(MVPStatemachine.this) {
				return pourMilk;
			}
		}
		
		protected void raisePourMilk() {
			synchronized(MVPStatemachine.this) {
				pourMilk = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onPourMilkRaised();
				}
			}
		}
		
		private boolean checkMilkOption;
		
		
		public boolean isRaisedCheckMilkOption() {
			synchronized(MVPStatemachine.this) {
				return checkMilkOption;
			}
		}
		
		protected void raiseCheckMilkOption() {
			synchronized(MVPStatemachine.this) {
				checkMilkOption = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onCheckMilkOptionRaised();
				}
			}
		}
		
		private boolean beginFirstStep;
		
		
		public boolean isRaisedBeginFirstStep() {
			synchronized(MVPStatemachine.this) {
				return beginFirstStep;
			}
		}
		
		protected void raiseBeginFirstStep() {
			synchronized(MVPStatemachine.this) {
				beginFirstStep = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onBeginFirstStepRaised();
				}
			}
		}
		
		private boolean automaticCancel;
		
		
		public boolean isRaisedAutomaticCancel() {
			synchronized(MVPStatemachine.this) {
				return automaticCancel;
			}
		}
		
		protected void raiseAutomaticCancel() {
			synchronized(MVPStatemachine.this) {
				automaticCancel = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onAutomaticCancelRaised();
				}
			}
		}
		
		private boolean sugarOrSyrup;
		
		
		public boolean isRaisedSugarOrSyrup() {
			synchronized(MVPStatemachine.this) {
				return sugarOrSyrup;
			}
		}
		
		protected void raiseSugarOrSyrup() {
			synchronized(MVPStatemachine.this) {
				sugarOrSyrup = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onSugarOrSyrupRaised();
				}
			}
		}
		
		protected void clearEvents() {
			optionButton = false;
			podPlacement = false;
			coffeeButton = false;
			teaButton = false;
			expressoButton = false;
			cancelButton = false;
			insertCoin10 = false;
			insertCoin25 = false;
			insertCoin50 = false;
			nFC = false;
			enoughMoneyInserted = false;
			cupPickedUp = false;
			positionnerDosette = false;
			seedGrind = false;
			bagPlacement = false;
			waitingForWater = false;
			endWaterHeat = false;
			endFirstStep = false;
			endSecondStep = false;
			step2Expresso = false;
			endPackSeed = false;
			waterHeated = false;
			waitForCup = false;
			cupIsPlaced = false;
			giveCup = false;
			cupIsTaken = false;
			letInfuse = false;
			milkButton = false;
			syrupButton = false;
			crustButton = false;
			vanillaButton = false;
			waterPoured = false;
			sugarAdded = false;
			syrupAdded = false;
			step1ElementPlaced = false;
			noMilkOption = false;
			milkOption = false;
			milkAdded = false;
			sugar = false;
			syrup = false;
		}
		protected void clearOutEvents() {
		
		vanillaChosed = false;
		syrupChosed = false;
		crustChosed = false;
		beginWaterHeat = false;
		milkChosed = false;
		disableMissingIngredients = false;
		beginMachineCleaning = false;
		addSugar = false;
		seedPacking = false;
		cupPlacing = false;
		bagPlacing = false;
		seedGrinding = false;
		podPlacing = false;
		waitForWaterPoured = false;
		waitForWaterHeated = false;
		coffeeChosed = false;
		teaChosed = false;
		expressoChosed = false;
		coin10Inserted = false;
		coin25Inserted = false;
		coin50Inserted = false;
		cancel = false;
		nFCPayment = false;
		doTransaction = false;
		endThirdStep = false;
		beginSecondStep = false;
		pourMilk = false;
		checkMilkOption = false;
		beginFirstStep = false;
		automaticCancel = false;
		sugarOrSyrup = false;
		}
		
	}
	
	
	protected SCInterfaceImpl sCInterface;
	
	private boolean initialized = false;
	
	public enum State {
		main_region_Step1,
		main_region_Step1_r1_Water_heat,
		main_region_Step1_r2_First_step,
		main_region_Step1_r2_Drink_difference,
		main_region_Step2,
		main_region_Step2_r1_Cup_Placement,
		main_region_Step2_r1_Cup_placed,
		main_region_Step2_r2_Drink_difference_step2,
		main_region_Step2_r2_ExpressoCase,
		main_region_Step2_r2_ExpressoCase_r1_PackSeed,
		main_region_Step2_r2_ExpressoCase_r2_WaitWater,
		main_region_Step2_r2_Waiting_for_water_to_heat,
		main_region_Step3,
		main_region_Step3_r1_Waiting_for_water_to_be_poured,
		main_region_Step3_r1_WaterPoured,
		main_region_Step3_r2_Milk_option__,
		main_region_Step3_r2_Waiting_for_milk_to_be_poured,
		main_region_Step3_r2_Waiting_for_sugar_to_be_added,
		main_region_Step3_r2_Sugar_or_mapple_syrup,
		main_region_Step3_r2_waiting_fo_mapple_syrup,
		main_region_Step3_r2_End_option,
		main_region_Choice_and_payment,
		main_region_Choice_and_payment_r1_No_drink_selected,
		main_region_Choice_and_payment_r1_Drink_selected____not_enough_money_inserted,
		main_region_Choice_and_payment_r1_Option_selected,
		main_region_WaitForCupToBeTaken,
		main_region_CleanMachine,
		main_region_Infusing,
		main_region_CheckIngredients,
		main_region_Drink_difference,
		$NullState$
	};
	
	private State[] historyVector = new State[1];
	private final State[] stateVector = new State[3];
	
	private int nextStateIndex;
	
	private ITimer timer;
	
	private final boolean[] timeEvents = new boolean[4];
	
	private BlockingQueue<Runnable> inEventQueue = new LinkedBlockingQueue<Runnable>();
	private boolean isRunningCycle = false;
	public MVPStatemachine() {
		sCInterface = new SCInterfaceImpl();
	}
	
	public synchronized void init() {
		this.initialized = true;
		if (timer == null) {
			throw new IllegalStateException("timer not set.");
		}
		for (int i = 0; i < 3; i++) {
			stateVector[i] = State.$NullState$;
		}
		for (int i = 0; i < 1; i++) {
			historyVector[i] = State.$NullState$;
		}
		clearEvents();
		clearOutEvents();
	}
	
	public synchronized void enter() {
		if (!initialized) {
			throw new IllegalStateException(
				"The state machine needs to be initialized first by calling the init() function."
			);
		}
		if (timer == null) {
			throw new IllegalStateException("timer not set.");
		}
		enterSequence_main_region_default();
	}
	
	public synchronized void runCycle() {
		if (!initialized)
			throw new IllegalStateException(
					"The state machine needs to be initialized first by calling the init() function.");
		
		if (isRunningCycle) {
			return;
		}
		isRunningCycle = true;
		
		clearOutEvents();
	
		Runnable task = getNextEvent();
		if (task == null) {
			task = getDefaultEvent();
		}
		
		while (task != null) {
			task.run();
			clearEvents();
			task = getNextEvent();
		}
		
		isRunningCycle = false;
	}
	
	protected synchronized void singleCycle() {
		for (nextStateIndex = 0; nextStateIndex < stateVector.length; nextStateIndex++) {
			switch (stateVector[nextStateIndex]) {
				case main_region_Step1_r1_Water_heat:
					main_region_Step1_r1_Water_heat_react(true);
					break;
				case main_region_Step1_r2_First_step:
					main_region_Step1_r2_First_step_react(true);
					break;
				case main_region_Step1_r2_Drink_difference:
					main_region_Step1_r2_Drink_difference_react(true);
					break;
				case main_region_Step2_r1_Cup_Placement:
					main_region_Step2_r1_Cup_Placement_react(true);
					break;
				case main_region_Step2_r1_Cup_placed:
					main_region_Step2_r1_Cup_placed_react(true);
					break;
				case main_region_Step2_r2_Drink_difference_step2:
					main_region_Step2_r2_Drink_difference_step2_react(true);
					break;
				case main_region_Step2_r2_ExpressoCase_r1_PackSeed:
					main_region_Step2_r2_ExpressoCase_r1_PackSeed_react(true);
					break;
				case main_region_Step2_r2_ExpressoCase_r2_WaitWater:
					main_region_Step2_r2_ExpressoCase_r2_WaitWater_react(true);
					break;
				case main_region_Step2_r2_Waiting_for_water_to_heat:
					main_region_Step2_r2_Waiting_for_water_to_heat_react(true);
					break;
				case main_region_Step3_r1_Waiting_for_water_to_be_poured:
					main_region_Step3_r1_Waiting_for_water_to_be_poured_react(true);
					break;
				case main_region_Step3_r1_WaterPoured:
					main_region_Step3_r1_WaterPoured_react(true);
					break;
				case main_region_Step3_r2_Milk_option__:
					main_region_Step3_r2_Milk_option___react(true);
					break;
				case main_region_Step3_r2_Waiting_for_milk_to_be_poured:
					main_region_Step3_r2_Waiting_for_milk_to_be_poured_react(true);
					break;
				case main_region_Step3_r2_Waiting_for_sugar_to_be_added:
					main_region_Step3_r2_Waiting_for_sugar_to_be_added_react(true);
					break;
				case main_region_Step3_r2_Sugar_or_mapple_syrup:
					main_region_Step3_r2_Sugar_or_mapple_syrup_react(true);
					break;
				case main_region_Step3_r2_waiting_fo_mapple_syrup:
					main_region_Step3_r2_waiting_fo_mapple_syrup_react(true);
					break;
				case main_region_Step3_r2_End_option:
					main_region_Step3_r2_End_option_react(true);
					break;
				case main_region_Choice_and_payment_r1_No_drink_selected:
					main_region_Choice_and_payment_r1_No_drink_selected_react(true);
					break;
				case main_region_Choice_and_payment_r1_Drink_selected____not_enough_money_inserted:
					main_region_Choice_and_payment_r1_Drink_selected____not_enough_money_inserted_react(true);
					break;
				case main_region_Choice_and_payment_r1_Option_selected:
					main_region_Choice_and_payment_r1_Option_selected_react(true);
					break;
				case main_region_WaitForCupToBeTaken:
					main_region_WaitForCupToBeTaken_react(true);
					break;
				case main_region_CleanMachine:
					main_region_CleanMachine_react(true);
					break;
				case main_region_Infusing:
					main_region_Infusing_react(true);
					break;
				case main_region_CheckIngredients:
					main_region_CheckIngredients_react(true);
					break;
				case main_region_Drink_difference:
					main_region_Drink_difference_react(true);
					break;
			default:
				// $NullState$
			}
		}
	}
	
	protected Runnable getNextEvent() {
		if(!inEventQueue.isEmpty()) {
			return inEventQueue.poll();
		}
		return null;
	}
	
	protected Runnable getDefaultEvent() {
		return new Runnable() {
			@Override
			public void run() {
				singleCycle();
			}
		};
	}
	
	public synchronized void exit() {
		exitSequence_main_region();
	}
	
	/**
	 * @see IStatemachine#isActive()
	 */
	public synchronized boolean isActive() {
		return stateVector[0] != State.$NullState$||stateVector[1] != State.$NullState$||stateVector[2] != State.$NullState$;
	}
	
	/** 
	* Always returns 'false' since this state machine can never become final.
	*
	* @see IStatemachine#isFinal()
	*/
	public synchronized boolean isFinal() {
		return false;
	}
	/**
	* This method resets the incoming events (time events included).
	*/
	protected void clearEvents() {
		sCInterface.clearEvents();
		for (int i=0; i<timeEvents.length; i++) {
			timeEvents[i] = false;
		}
	}
	
	/**
	* This method resets the outgoing events.
	*/
	protected void clearOutEvents() {
		sCInterface.clearOutEvents();
	}
	
	/**
	* Returns true if the given state is currently active otherwise false.
	*/
	public synchronized boolean isStateActive(State state) {
	
		switch (state) {
		case main_region_Step1:
			return stateVector[0].ordinal() >= State.
					main_region_Step1.ordinal()&& stateVector[0].ordinal() <= State.main_region_Step1_r2_Drink_difference.ordinal();
		case main_region_Step1_r1_Water_heat:
			return stateVector[0] == State.main_region_Step1_r1_Water_heat;
		case main_region_Step1_r2_First_step:
			return stateVector[1] == State.main_region_Step1_r2_First_step;
		case main_region_Step1_r2_Drink_difference:
			return stateVector[1] == State.main_region_Step1_r2_Drink_difference;
		case main_region_Step2:
			return stateVector[0].ordinal() >= State.
					main_region_Step2.ordinal()&& stateVector[0].ordinal() <= State.main_region_Step2_r2_Waiting_for_water_to_heat.ordinal();
		case main_region_Step2_r1_Cup_Placement:
			return stateVector[0] == State.main_region_Step2_r1_Cup_Placement;
		case main_region_Step2_r1_Cup_placed:
			return stateVector[0] == State.main_region_Step2_r1_Cup_placed;
		case main_region_Step2_r2_Drink_difference_step2:
			return stateVector[1] == State.main_region_Step2_r2_Drink_difference_step2;
		case main_region_Step2_r2_ExpressoCase:
			return stateVector[1].ordinal() >= State.
					main_region_Step2_r2_ExpressoCase.ordinal()&& stateVector[1].ordinal() <= State.main_region_Step2_r2_ExpressoCase_r2_WaitWater.ordinal();
		case main_region_Step2_r2_ExpressoCase_r1_PackSeed:
			return stateVector[1] == State.main_region_Step2_r2_ExpressoCase_r1_PackSeed;
		case main_region_Step2_r2_ExpressoCase_r2_WaitWater:
			return stateVector[2] == State.main_region_Step2_r2_ExpressoCase_r2_WaitWater;
		case main_region_Step2_r2_Waiting_for_water_to_heat:
			return stateVector[1] == State.main_region_Step2_r2_Waiting_for_water_to_heat;
		case main_region_Step3:
			return stateVector[0].ordinal() >= State.
					main_region_Step3.ordinal()&& stateVector[0].ordinal() <= State.main_region_Step3_r2_End_option.ordinal();
		case main_region_Step3_r1_Waiting_for_water_to_be_poured:
			return stateVector[0] == State.main_region_Step3_r1_Waiting_for_water_to_be_poured;
		case main_region_Step3_r1_WaterPoured:
			return stateVector[0] == State.main_region_Step3_r1_WaterPoured;
		case main_region_Step3_r2_Milk_option__:
			return stateVector[1] == State.main_region_Step3_r2_Milk_option__;
		case main_region_Step3_r2_Waiting_for_milk_to_be_poured:
			return stateVector[1] == State.main_region_Step3_r2_Waiting_for_milk_to_be_poured;
		case main_region_Step3_r2_Waiting_for_sugar_to_be_added:
			return stateVector[1] == State.main_region_Step3_r2_Waiting_for_sugar_to_be_added;
		case main_region_Step3_r2_Sugar_or_mapple_syrup:
			return stateVector[1] == State.main_region_Step3_r2_Sugar_or_mapple_syrup;
		case main_region_Step3_r2_waiting_fo_mapple_syrup:
			return stateVector[1] == State.main_region_Step3_r2_waiting_fo_mapple_syrup;
		case main_region_Step3_r2_End_option:
			return stateVector[1] == State.main_region_Step3_r2_End_option;
		case main_region_Choice_and_payment:
			return stateVector[0].ordinal() >= State.
					main_region_Choice_and_payment.ordinal()&& stateVector[0].ordinal() <= State.main_region_Choice_and_payment_r1_Option_selected.ordinal();
		case main_region_Choice_and_payment_r1_No_drink_selected:
			return stateVector[0] == State.main_region_Choice_and_payment_r1_No_drink_selected;
		case main_region_Choice_and_payment_r1_Drink_selected____not_enough_money_inserted:
			return stateVector[0] == State.main_region_Choice_and_payment_r1_Drink_selected____not_enough_money_inserted;
		case main_region_Choice_and_payment_r1_Option_selected:
			return stateVector[0] == State.main_region_Choice_and_payment_r1_Option_selected;
		case main_region_WaitForCupToBeTaken:
			return stateVector[0] == State.main_region_WaitForCupToBeTaken;
		case main_region_CleanMachine:
			return stateVector[0] == State.main_region_CleanMachine;
		case main_region_Infusing:
			return stateVector[0] == State.main_region_Infusing;
		case main_region_CheckIngredients:
			return stateVector[0] == State.main_region_CheckIngredients;
		case main_region_Drink_difference:
			return stateVector[0] == State.main_region_Drink_difference;
		default:
			return false;
		}
	}
	
	/**
	* Set the {@link ITimer} for the state machine. It must be set
	* externally on a timed state machine before a run cycle can be correctly
	* executed.
	* 
	* @param timer
	*/
	public synchronized void setTimer(ITimer timer) {
		this.timer = timer;
	}
	
	/**
	* Returns the currently used timer.
	* 
	* @return {@link ITimer}
	*/
	public ITimer getTimer() {
		return timer;
	}
	
	public synchronized void timeElapsed(int eventID) {
		inEventQueue.add(new Runnable() {
			@Override
			public void run() {
				timeEvents[eventID] = true;
				singleCycle();
			}
		});
		runCycle();
	}
	
	public SCInterface getSCInterface() {
		return sCInterface;
	}
	
	public synchronized void raiseOptionButton() {
		sCInterface.raiseOptionButton();
	}
	
	public synchronized void raisePodPlacement() {
		sCInterface.raisePodPlacement();
	}
	
	public synchronized void raiseCoffeeButton() {
		sCInterface.raiseCoffeeButton();
	}
	
	public synchronized void raiseTeaButton() {
		sCInterface.raiseTeaButton();
	}
	
	public synchronized void raiseExpressoButton() {
		sCInterface.raiseExpressoButton();
	}
	
	public synchronized void raiseCancelButton() {
		sCInterface.raiseCancelButton();
	}
	
	public synchronized void raiseInsertCoin10() {
		sCInterface.raiseInsertCoin10();
	}
	
	public synchronized void raiseInsertCoin25() {
		sCInterface.raiseInsertCoin25();
	}
	
	public synchronized void raiseInsertCoin50() {
		sCInterface.raiseInsertCoin50();
	}
	
	public synchronized void raiseNFC() {
		sCInterface.raiseNFC();
	}
	
	public synchronized void raiseEnoughMoneyInserted() {
		sCInterface.raiseEnoughMoneyInserted();
	}
	
	public synchronized void raiseCupPickedUp() {
		sCInterface.raiseCupPickedUp();
	}
	
	public synchronized void raisePositionnerDosette() {
		sCInterface.raisePositionnerDosette();
	}
	
	public synchronized void raiseSeedGrind() {
		sCInterface.raiseSeedGrind();
	}
	
	public synchronized void raiseBagPlacement() {
		sCInterface.raiseBagPlacement();
	}
	
	public synchronized void raiseWaitingForWater() {
		sCInterface.raiseWaitingForWater();
	}
	
	public synchronized void raiseEndWaterHeat() {
		sCInterface.raiseEndWaterHeat();
	}
	
	public synchronized void raiseEndFirstStep() {
		sCInterface.raiseEndFirstStep();
	}
	
	public synchronized void raiseEndSecondStep() {
		sCInterface.raiseEndSecondStep();
	}
	
	public synchronized void raiseStep2Expresso() {
		sCInterface.raiseStep2Expresso();
	}
	
	public synchronized void raiseEndPackSeed() {
		sCInterface.raiseEndPackSeed();
	}
	
	public synchronized void raiseWaterHeated() {
		sCInterface.raiseWaterHeated();
	}
	
	public synchronized void raiseWaitForCup() {
		sCInterface.raiseWaitForCup();
	}
	
	public synchronized void raiseCupIsPlaced() {
		sCInterface.raiseCupIsPlaced();
	}
	
	public synchronized void raiseGiveCup() {
		sCInterface.raiseGiveCup();
	}
	
	public synchronized void raiseCupIsTaken() {
		sCInterface.raiseCupIsTaken();
	}
	
	public synchronized void raiseLetInfuse() {
		sCInterface.raiseLetInfuse();
	}
	
	public synchronized void raiseMilkButton() {
		sCInterface.raiseMilkButton();
	}
	
	public synchronized void raiseSyrupButton() {
		sCInterface.raiseSyrupButton();
	}
	
	public synchronized void raiseCrustButton() {
		sCInterface.raiseCrustButton();
	}
	
	public synchronized void raiseVanillaButton() {
		sCInterface.raiseVanillaButton();
	}
	
	public synchronized void raiseWaterPoured() {
		sCInterface.raiseWaterPoured();
	}
	
	public synchronized void raiseSugarAdded() {
		sCInterface.raiseSugarAdded();
	}
	
	public synchronized void raiseSyrupAdded() {
		sCInterface.raiseSyrupAdded();
	}
	
	public synchronized void raiseStep1ElementPlaced() {
		sCInterface.raiseStep1ElementPlaced();
	}
	
	public synchronized void raiseNoMilkOption() {
		sCInterface.raiseNoMilkOption();
	}
	
	public synchronized void raiseMilkOption() {
		sCInterface.raiseMilkOption();
	}
	
	public synchronized void raiseMilkAdded() {
		sCInterface.raiseMilkAdded();
	}
	
	public synchronized void raiseSugar() {
		sCInterface.raiseSugar();
	}
	
	public synchronized void raiseSyrup() {
		sCInterface.raiseSyrup();
	}
	
	public synchronized boolean isRaisedVanillaChosed() {
		return sCInterface.isRaisedVanillaChosed();
	}
	
	public synchronized boolean isRaisedSyrupChosed() {
		return sCInterface.isRaisedSyrupChosed();
	}
	
	public synchronized boolean isRaisedCrustChosed() {
		return sCInterface.isRaisedCrustChosed();
	}
	
	public synchronized boolean isRaisedBeginWaterHeat() {
		return sCInterface.isRaisedBeginWaterHeat();
	}
	
	public synchronized boolean isRaisedMilkChosed() {
		return sCInterface.isRaisedMilkChosed();
	}
	
	public synchronized boolean isRaisedDisableMissingIngredients() {
		return sCInterface.isRaisedDisableMissingIngredients();
	}
	
	public synchronized boolean isRaisedBeginMachineCleaning() {
		return sCInterface.isRaisedBeginMachineCleaning();
	}
	
	public synchronized boolean isRaisedAddSugar() {
		return sCInterface.isRaisedAddSugar();
	}
	
	public synchronized boolean isRaisedSeedPacking() {
		return sCInterface.isRaisedSeedPacking();
	}
	
	public synchronized boolean isRaisedCupPlacing() {
		return sCInterface.isRaisedCupPlacing();
	}
	
	public synchronized boolean isRaisedBagPlacing() {
		return sCInterface.isRaisedBagPlacing();
	}
	
	public synchronized boolean isRaisedSeedGrinding() {
		return sCInterface.isRaisedSeedGrinding();
	}
	
	public synchronized boolean isRaisedPodPlacing() {
		return sCInterface.isRaisedPodPlacing();
	}
	
	public synchronized boolean isRaisedWaitForWaterPoured() {
		return sCInterface.isRaisedWaitForWaterPoured();
	}
	
	public synchronized boolean isRaisedWaitForWaterHeated() {
		return sCInterface.isRaisedWaitForWaterHeated();
	}
	
	public synchronized boolean isRaisedCoffeeChosed() {
		return sCInterface.isRaisedCoffeeChosed();
	}
	
	public synchronized boolean isRaisedTeaChosed() {
		return sCInterface.isRaisedTeaChosed();
	}
	
	public synchronized boolean isRaisedExpressoChosed() {
		return sCInterface.isRaisedExpressoChosed();
	}
	
	public synchronized boolean isRaisedCoin10Inserted() {
		return sCInterface.isRaisedCoin10Inserted();
	}
	
	public synchronized boolean isRaisedCoin25Inserted() {
		return sCInterface.isRaisedCoin25Inserted();
	}
	
	public synchronized boolean isRaisedCoin50Inserted() {
		return sCInterface.isRaisedCoin50Inserted();
	}
	
	public synchronized boolean isRaisedCancel() {
		return sCInterface.isRaisedCancel();
	}
	
	public synchronized boolean isRaisedNFCPayment() {
		return sCInterface.isRaisedNFCPayment();
	}
	
	public synchronized boolean isRaisedDoTransaction() {
		return sCInterface.isRaisedDoTransaction();
	}
	
	public synchronized boolean isRaisedEndThirdStep() {
		return sCInterface.isRaisedEndThirdStep();
	}
	
	public synchronized boolean isRaisedBeginSecondStep() {
		return sCInterface.isRaisedBeginSecondStep();
	}
	
	public synchronized boolean isRaisedPourMilk() {
		return sCInterface.isRaisedPourMilk();
	}
	
	public synchronized boolean isRaisedCheckMilkOption() {
		return sCInterface.isRaisedCheckMilkOption();
	}
	
	public synchronized boolean isRaisedBeginFirstStep() {
		return sCInterface.isRaisedBeginFirstStep();
	}
	
	public synchronized boolean isRaisedAutomaticCancel() {
		return sCInterface.isRaisedAutomaticCancel();
	}
	
	public synchronized boolean isRaisedSugarOrSyrup() {
		return sCInterface.isRaisedSugarOrSyrup();
	}
	
	/* Entry action for state 'Water heat'. */
	private void entryAction_main_region_Step1_r1_Water_heat() {
		sCInterface.raiseBeginWaterHeat();
	}
	
	/* Entry action for state 'Drink difference'. */
	private void entryAction_main_region_Step1_r2_Drink_difference() {
		sCInterface.raiseBeginFirstStep();
	}
	
	/* Entry action for state 'Cup Placement'. */
	private void entryAction_main_region_Step2_r1_Cup_Placement() {
		timer.setTimer(this, 0, 3000, false);
		
		sCInterface.raiseCupPlacing();
	}
	
	/* Entry action for state 'Drink difference step2'. */
	private void entryAction_main_region_Step2_r2_Drink_difference_step2() {
		sCInterface.raiseBeginSecondStep();
	}
	
	/* Entry action for state 'PackSeed'. */
	private void entryAction_main_region_Step2_r2_ExpressoCase_r1_PackSeed() {
		sCInterface.raiseSeedPacking();
	}
	
	/* Entry action for state 'WaitWater'. */
	private void entryAction_main_region_Step2_r2_ExpressoCase_r2_WaitWater() {
		sCInterface.raiseWaitForWaterHeated();
	}
	
	/* Entry action for state 'Waiting for water to be poured'. */
	private void entryAction_main_region_Step3_r1_Waiting_for_water_to_be_poured() {
		sCInterface.raiseWaitForWaterPoured();
	}
	
	/* Entry action for state 'Milk option ?'. */
	private void entryAction_main_region_Step3_r2_Milk_option__() {
		sCInterface.raiseCheckMilkOption();
	}
	
	/* Entry action for state 'Waiting for milk to be poured'. */
	private void entryAction_main_region_Step3_r2_Waiting_for_milk_to_be_poured() {
		sCInterface.raisePourMilk();
	}
	
	/* Entry action for state 'Sugar or mapple syrup'. */
	private void entryAction_main_region_Step3_r2_Sugar_or_mapple_syrup() {
		sCInterface.raiseSugarOrSyrup();
	}
	
	/* Entry action for state 'Choice and payment'. */
	private void entryAction_main_region_Choice_and_payment() {
		timer.setTimer(this, 1, 5000, false);
	}
	
	/* Entry action for state 'CleanMachine'. */
	private void entryAction_main_region_CleanMachine() {
		timer.setTimer(this, 2, 10000, false);
		
		sCInterface.raiseBeginMachineCleaning();
	}
	
	/* Entry action for state 'CheckIngredients'. */
	private void entryAction_main_region_CheckIngredients() {
		timer.setTimer(this, 3, 10, false);
	}
	
	/* Entry action for state 'Drink difference'. */
	private void entryAction_main_region_Drink_difference() {
		sCInterface.raiseEndThirdStep();
	}
	
	/* Exit action for state 'Cup Placement'. */
	private void exitAction_main_region_Step2_r1_Cup_Placement() {
		timer.unsetTimer(this, 0);
	}
	
	/* Exit action for state 'Choice and payment'. */
	private void exitAction_main_region_Choice_and_payment() {
		timer.unsetTimer(this, 1);
	}
	
	/* Exit action for state 'CleanMachine'. */
	private void exitAction_main_region_CleanMachine() {
		timer.unsetTimer(this, 2);
	}
	
	/* Exit action for state 'CheckIngredients'. */
	private void exitAction_main_region_CheckIngredients() {
		timer.unsetTimer(this, 3);
	}
	
	/* 'default' enter sequence for state Step1 */
	private void enterSequence_main_region_Step1_default() {
		enterSequence_main_region_Step1_r1_default();
		enterSequence_main_region_Step1_r2_default();
	}
	
	/* 'default' enter sequence for state Water heat */
	private void enterSequence_main_region_Step1_r1_Water_heat_default() {
		entryAction_main_region_Step1_r1_Water_heat();
		nextStateIndex = 0;
		stateVector[0] = State.main_region_Step1_r1_Water_heat;
	}
	
	/* 'default' enter sequence for state First step */
	private void enterSequence_main_region_Step1_r2_First_step_default() {
		nextStateIndex = 1;
		stateVector[1] = State.main_region_Step1_r2_First_step;
	}
	
	/* 'default' enter sequence for state Drink difference */
	private void enterSequence_main_region_Step1_r2_Drink_difference_default() {
		entryAction_main_region_Step1_r2_Drink_difference();
		nextStateIndex = 1;
		stateVector[1] = State.main_region_Step1_r2_Drink_difference;
	}
	
	/* 'default' enter sequence for state Step2 */
	private void enterSequence_main_region_Step2_default() {
		enterSequence_main_region_Step2_r1_default();
		enterSequence_main_region_Step2_r2_default();
	}
	
	/* 'default' enter sequence for state Cup Placement */
	private void enterSequence_main_region_Step2_r1_Cup_Placement_default() {
		entryAction_main_region_Step2_r1_Cup_Placement();
		nextStateIndex = 0;
		stateVector[0] = State.main_region_Step2_r1_Cup_Placement;
	}
	
	/* 'default' enter sequence for state Cup placed */
	private void enterSequence_main_region_Step2_r1_Cup_placed_default() {
		nextStateIndex = 0;
		stateVector[0] = State.main_region_Step2_r1_Cup_placed;
	}
	
	/* 'default' enter sequence for state Drink difference step2 */
	private void enterSequence_main_region_Step2_r2_Drink_difference_step2_default() {
		entryAction_main_region_Step2_r2_Drink_difference_step2();
		nextStateIndex = 1;
		stateVector[1] = State.main_region_Step2_r2_Drink_difference_step2;
	}
	
	/* 'default' enter sequence for state ExpressoCase */
	private void enterSequence_main_region_Step2_r2_ExpressoCase_default() {
		enterSequence_main_region_Step2_r2_ExpressoCase_r1_default();
		enterSequence_main_region_Step2_r2_ExpressoCase_r2_default();
	}
	
	/* 'default' enter sequence for state PackSeed */
	private void enterSequence_main_region_Step2_r2_ExpressoCase_r1_PackSeed_default() {
		entryAction_main_region_Step2_r2_ExpressoCase_r1_PackSeed();
		nextStateIndex = 1;
		stateVector[1] = State.main_region_Step2_r2_ExpressoCase_r1_PackSeed;
	}
	
	/* 'default' enter sequence for state WaitWater */
	private void enterSequence_main_region_Step2_r2_ExpressoCase_r2_WaitWater_default() {
		entryAction_main_region_Step2_r2_ExpressoCase_r2_WaitWater();
		nextStateIndex = 2;
		stateVector[2] = State.main_region_Step2_r2_ExpressoCase_r2_WaitWater;
	}
	
	/* 'default' enter sequence for state Waiting for water to heat */
	private void enterSequence_main_region_Step2_r2_Waiting_for_water_to_heat_default() {
		nextStateIndex = 1;
		stateVector[1] = State.main_region_Step2_r2_Waiting_for_water_to_heat;
	}
	
	/* 'default' enter sequence for state Step3 */
	private void enterSequence_main_region_Step3_default() {
		enterSequence_main_region_Step3_r1_default();
		enterSequence_main_region_Step3_r2_default();
	}
	
	/* 'default' enter sequence for state Waiting for water to be poured */
	private void enterSequence_main_region_Step3_r1_Waiting_for_water_to_be_poured_default() {
		entryAction_main_region_Step3_r1_Waiting_for_water_to_be_poured();
		nextStateIndex = 0;
		stateVector[0] = State.main_region_Step3_r1_Waiting_for_water_to_be_poured;
	}
	
	/* 'default' enter sequence for state WaterPoured */
	private void enterSequence_main_region_Step3_r1_WaterPoured_default() {
		nextStateIndex = 0;
		stateVector[0] = State.main_region_Step3_r1_WaterPoured;
	}
	
	/* 'default' enter sequence for state Milk option ? */
	private void enterSequence_main_region_Step3_r2_Milk_option___default() {
		entryAction_main_region_Step3_r2_Milk_option__();
		nextStateIndex = 1;
		stateVector[1] = State.main_region_Step3_r2_Milk_option__;
	}
	
	/* 'default' enter sequence for state Waiting for milk to be poured */
	private void enterSequence_main_region_Step3_r2_Waiting_for_milk_to_be_poured_default() {
		entryAction_main_region_Step3_r2_Waiting_for_milk_to_be_poured();
		nextStateIndex = 1;
		stateVector[1] = State.main_region_Step3_r2_Waiting_for_milk_to_be_poured;
	}
	
	/* 'default' enter sequence for state Waiting for sugar to be added */
	private void enterSequence_main_region_Step3_r2_Waiting_for_sugar_to_be_added_default() {
		nextStateIndex = 1;
		stateVector[1] = State.main_region_Step3_r2_Waiting_for_sugar_to_be_added;
	}
	
	/* 'default' enter sequence for state Sugar or mapple syrup */
	private void enterSequence_main_region_Step3_r2_Sugar_or_mapple_syrup_default() {
		entryAction_main_region_Step3_r2_Sugar_or_mapple_syrup();
		nextStateIndex = 1;
		stateVector[1] = State.main_region_Step3_r2_Sugar_or_mapple_syrup;
	}
	
	/* 'default' enter sequence for state waiting fo mapple syrup */
	private void enterSequence_main_region_Step3_r2_waiting_fo_mapple_syrup_default() {
		nextStateIndex = 1;
		stateVector[1] = State.main_region_Step3_r2_waiting_fo_mapple_syrup;
	}
	
	/* 'default' enter sequence for state End option */
	private void enterSequence_main_region_Step3_r2_End_option_default() {
		nextStateIndex = 1;
		stateVector[1] = State.main_region_Step3_r2_End_option;
	}
	
	/* 'default' enter sequence for state Choice and payment */
	private void enterSequence_main_region_Choice_and_payment_default() {
		entryAction_main_region_Choice_and_payment();
		enterSequence_main_region_Choice_and_payment_r1_default();
	}
	
	/* 'default' enter sequence for state No_drink_selected */
	private void enterSequence_main_region_Choice_and_payment_r1_No_drink_selected_default() {
		nextStateIndex = 0;
		stateVector[0] = State.main_region_Choice_and_payment_r1_No_drink_selected;
		
		historyVector[0] = stateVector[0];
	}
	
	/* 'default' enter sequence for state Drink selected && not enough money inserted */
	private void enterSequence_main_region_Choice_and_payment_r1_Drink_selected____not_enough_money_inserted_default() {
		nextStateIndex = 0;
		stateVector[0] = State.main_region_Choice_and_payment_r1_Drink_selected____not_enough_money_inserted;
		
		historyVector[0] = stateVector[0];
	}
	
	/* 'default' enter sequence for state Option selected */
	private void enterSequence_main_region_Choice_and_payment_r1_Option_selected_default() {
		nextStateIndex = 0;
		stateVector[0] = State.main_region_Choice_and_payment_r1_Option_selected;
		
		historyVector[0] = stateVector[0];
	}
	
	/* 'default' enter sequence for state WaitForCupToBeTaken */
	private void enterSequence_main_region_WaitForCupToBeTaken_default() {
		nextStateIndex = 0;
		stateVector[0] = State.main_region_WaitForCupToBeTaken;
	}
	
	/* 'default' enter sequence for state CleanMachine */
	private void enterSequence_main_region_CleanMachine_default() {
		entryAction_main_region_CleanMachine();
		nextStateIndex = 0;
		stateVector[0] = State.main_region_CleanMachine;
	}
	
	/* 'default' enter sequence for state Infusing */
	private void enterSequence_main_region_Infusing_default() {
		nextStateIndex = 0;
		stateVector[0] = State.main_region_Infusing;
	}
	
	/* 'default' enter sequence for state CheckIngredients */
	private void enterSequence_main_region_CheckIngredients_default() {
		entryAction_main_region_CheckIngredients();
		nextStateIndex = 0;
		stateVector[0] = State.main_region_CheckIngredients;
	}
	
	/* 'default' enter sequence for state Drink difference */
	private void enterSequence_main_region_Drink_difference_default() {
		entryAction_main_region_Drink_difference();
		nextStateIndex = 0;
		stateVector[0] = State.main_region_Drink_difference;
	}
	
	/* 'default' enter sequence for region main region */
	private void enterSequence_main_region_default() {
		react_main_region__entry_Default();
	}
	
	/* 'default' enter sequence for region r1 */
	private void enterSequence_main_region_Step1_r1_default() {
		react_main_region_Step1_r1__entry_Default();
	}
	
	/* 'default' enter sequence for region r2 */
	private void enterSequence_main_region_Step1_r2_default() {
		react_main_region_Step1_r2__entry_Default();
	}
	
	/* 'default' enter sequence for region r1 */
	private void enterSequence_main_region_Step2_r1_default() {
		react_main_region_Step2_r1__entry_Default();
	}
	
	/* 'default' enter sequence for region r2 */
	private void enterSequence_main_region_Step2_r2_default() {
		react_main_region_Step2_r2__entry_Default();
	}
	
	/* 'default' enter sequence for region r1 */
	private void enterSequence_main_region_Step2_r2_ExpressoCase_r1_default() {
		react_main_region_Step2_r2_ExpressoCase_r1__entry_Default();
	}
	
	/* 'default' enter sequence for region r2 */
	private void enterSequence_main_region_Step2_r2_ExpressoCase_r2_default() {
		react_main_region_Step2_r2_ExpressoCase_r2__entry_Default();
	}
	
	/* 'default' enter sequence for region r1 */
	private void enterSequence_main_region_Step3_r1_default() {
		react_main_region_Step3_r1__entry_Default();
	}
	
	/* 'default' enter sequence for region r2 */
	private void enterSequence_main_region_Step3_r2_default() {
		react_main_region_Step3_r2__entry_Default();
	}
	
	/* 'default' enter sequence for region r1 */
	private void enterSequence_main_region_Choice_and_payment_r1_default() {
		react_main_region_Choice_and_payment_r1__entry_Default();
	}
	
	/* deep enterSequence with history in child r1 */
	private void deepEnterSequence_main_region_Choice_and_payment_r1() {
		switch (historyVector[0]) {
		case main_region_Choice_and_payment_r1_No_drink_selected:
			enterSequence_main_region_Choice_and_payment_r1_No_drink_selected_default();
			break;
		case main_region_Choice_and_payment_r1_Drink_selected____not_enough_money_inserted:
			enterSequence_main_region_Choice_and_payment_r1_Drink_selected____not_enough_money_inserted_default();
			break;
		case main_region_Choice_and_payment_r1_Option_selected:
			enterSequence_main_region_Choice_and_payment_r1_Option_selected_default();
			break;
		default:
			break;
		}
	}
	
	/* Default exit sequence for state Step1 */
	private void exitSequence_main_region_Step1() {
		exitSequence_main_region_Step1_r1();
		exitSequence_main_region_Step1_r2();
	}
	
	/* Default exit sequence for state Water heat */
	private void exitSequence_main_region_Step1_r1_Water_heat() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
	}
	
	/* Default exit sequence for state First step */
	private void exitSequence_main_region_Step1_r2_First_step() {
		nextStateIndex = 1;
		stateVector[1] = State.$NullState$;
	}
	
	/* Default exit sequence for state Drink difference */
	private void exitSequence_main_region_Step1_r2_Drink_difference() {
		nextStateIndex = 1;
		stateVector[1] = State.$NullState$;
	}
	
	/* Default exit sequence for state Step2 */
	private void exitSequence_main_region_Step2() {
		exitSequence_main_region_Step2_r1();
		exitSequence_main_region_Step2_r2();
	}
	
	/* Default exit sequence for state Cup Placement */
	private void exitSequence_main_region_Step2_r1_Cup_Placement() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
		
		exitAction_main_region_Step2_r1_Cup_Placement();
	}
	
	/* Default exit sequence for state Cup placed */
	private void exitSequence_main_region_Step2_r1_Cup_placed() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
	}
	
	/* Default exit sequence for state Drink difference step2 */
	private void exitSequence_main_region_Step2_r2_Drink_difference_step2() {
		nextStateIndex = 1;
		stateVector[1] = State.$NullState$;
	}
	
	/* Default exit sequence for state ExpressoCase */
	private void exitSequence_main_region_Step2_r2_ExpressoCase() {
		exitSequence_main_region_Step2_r2_ExpressoCase_r1();
		exitSequence_main_region_Step2_r2_ExpressoCase_r2();
	}
	
	/* Default exit sequence for state PackSeed */
	private void exitSequence_main_region_Step2_r2_ExpressoCase_r1_PackSeed() {
		nextStateIndex = 1;
		stateVector[1] = State.$NullState$;
	}
	
	/* Default exit sequence for state WaitWater */
	private void exitSequence_main_region_Step2_r2_ExpressoCase_r2_WaitWater() {
		nextStateIndex = 2;
		stateVector[2] = State.$NullState$;
	}
	
	/* Default exit sequence for state Waiting for water to heat */
	private void exitSequence_main_region_Step2_r2_Waiting_for_water_to_heat() {
		nextStateIndex = 1;
		stateVector[1] = State.$NullState$;
	}
	
	/* Default exit sequence for state Step3 */
	private void exitSequence_main_region_Step3() {
		exitSequence_main_region_Step3_r1();
		exitSequence_main_region_Step3_r2();
	}
	
	/* Default exit sequence for state Waiting for water to be poured */
	private void exitSequence_main_region_Step3_r1_Waiting_for_water_to_be_poured() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
	}
	
	/* Default exit sequence for state WaterPoured */
	private void exitSequence_main_region_Step3_r1_WaterPoured() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
	}
	
	/* Default exit sequence for state Milk option ? */
	private void exitSequence_main_region_Step3_r2_Milk_option__() {
		nextStateIndex = 1;
		stateVector[1] = State.$NullState$;
	}
	
	/* Default exit sequence for state Waiting for milk to be poured */
	private void exitSequence_main_region_Step3_r2_Waiting_for_milk_to_be_poured() {
		nextStateIndex = 1;
		stateVector[1] = State.$NullState$;
	}
	
	/* Default exit sequence for state Waiting for sugar to be added */
	private void exitSequence_main_region_Step3_r2_Waiting_for_sugar_to_be_added() {
		nextStateIndex = 1;
		stateVector[1] = State.$NullState$;
	}
	
	/* Default exit sequence for state Sugar or mapple syrup */
	private void exitSequence_main_region_Step3_r2_Sugar_or_mapple_syrup() {
		nextStateIndex = 1;
		stateVector[1] = State.$NullState$;
	}
	
	/* Default exit sequence for state waiting fo mapple syrup */
	private void exitSequence_main_region_Step3_r2_waiting_fo_mapple_syrup() {
		nextStateIndex = 1;
		stateVector[1] = State.$NullState$;
	}
	
	/* Default exit sequence for state End option */
	private void exitSequence_main_region_Step3_r2_End_option() {
		nextStateIndex = 1;
		stateVector[1] = State.$NullState$;
	}
	
	/* Default exit sequence for state Choice and payment */
	private void exitSequence_main_region_Choice_and_payment() {
		exitSequence_main_region_Choice_and_payment_r1();
		exitAction_main_region_Choice_and_payment();
	}
	
	/* Default exit sequence for state No_drink_selected */
	private void exitSequence_main_region_Choice_and_payment_r1_No_drink_selected() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
	}
	
	/* Default exit sequence for state Drink selected && not enough money inserted */
	private void exitSequence_main_region_Choice_and_payment_r1_Drink_selected____not_enough_money_inserted() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
	}
	
	/* Default exit sequence for state Option selected */
	private void exitSequence_main_region_Choice_and_payment_r1_Option_selected() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
	}
	
	/* Default exit sequence for state WaitForCupToBeTaken */
	private void exitSequence_main_region_WaitForCupToBeTaken() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
	}
	
	/* Default exit sequence for state CleanMachine */
	private void exitSequence_main_region_CleanMachine() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
		
		exitAction_main_region_CleanMachine();
	}
	
	/* Default exit sequence for state Infusing */
	private void exitSequence_main_region_Infusing() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
	}
	
	/* Default exit sequence for state CheckIngredients */
	private void exitSequence_main_region_CheckIngredients() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
		
		exitAction_main_region_CheckIngredients();
	}
	
	/* Default exit sequence for state Drink difference */
	private void exitSequence_main_region_Drink_difference() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
	}
	
	/* Default exit sequence for region main region */
	private void exitSequence_main_region() {
		switch (stateVector[0]) {
		case main_region_Step1_r1_Water_heat:
			exitSequence_main_region_Step1_r1_Water_heat();
			break;
		case main_region_Step2_r1_Cup_Placement:
			exitSequence_main_region_Step2_r1_Cup_Placement();
			break;
		case main_region_Step2_r1_Cup_placed:
			exitSequence_main_region_Step2_r1_Cup_placed();
			break;
		case main_region_Step3_r1_Waiting_for_water_to_be_poured:
			exitSequence_main_region_Step3_r1_Waiting_for_water_to_be_poured();
			break;
		case main_region_Step3_r1_WaterPoured:
			exitSequence_main_region_Step3_r1_WaterPoured();
			break;
		case main_region_Choice_and_payment_r1_No_drink_selected:
			exitSequence_main_region_Choice_and_payment_r1_No_drink_selected();
			exitAction_main_region_Choice_and_payment();
			break;
		case main_region_Choice_and_payment_r1_Drink_selected____not_enough_money_inserted:
			exitSequence_main_region_Choice_and_payment_r1_Drink_selected____not_enough_money_inserted();
			exitAction_main_region_Choice_and_payment();
			break;
		case main_region_Choice_and_payment_r1_Option_selected:
			exitSequence_main_region_Choice_and_payment_r1_Option_selected();
			exitAction_main_region_Choice_and_payment();
			break;
		case main_region_WaitForCupToBeTaken:
			exitSequence_main_region_WaitForCupToBeTaken();
			break;
		case main_region_CleanMachine:
			exitSequence_main_region_CleanMachine();
			break;
		case main_region_Infusing:
			exitSequence_main_region_Infusing();
			break;
		case main_region_CheckIngredients:
			exitSequence_main_region_CheckIngredients();
			break;
		case main_region_Drink_difference:
			exitSequence_main_region_Drink_difference();
			break;
		default:
			break;
		}
		
		switch (stateVector[1]) {
		case main_region_Step1_r2_First_step:
			exitSequence_main_region_Step1_r2_First_step();
			break;
		case main_region_Step1_r2_Drink_difference:
			exitSequence_main_region_Step1_r2_Drink_difference();
			break;
		case main_region_Step2_r2_Drink_difference_step2:
			exitSequence_main_region_Step2_r2_Drink_difference_step2();
			break;
		case main_region_Step2_r2_ExpressoCase_r1_PackSeed:
			exitSequence_main_region_Step2_r2_ExpressoCase_r1_PackSeed();
			break;
		case main_region_Step2_r2_Waiting_for_water_to_heat:
			exitSequence_main_region_Step2_r2_Waiting_for_water_to_heat();
			break;
		case main_region_Step3_r2_Milk_option__:
			exitSequence_main_region_Step3_r2_Milk_option__();
			break;
		case main_region_Step3_r2_Waiting_for_milk_to_be_poured:
			exitSequence_main_region_Step3_r2_Waiting_for_milk_to_be_poured();
			break;
		case main_region_Step3_r2_Waiting_for_sugar_to_be_added:
			exitSequence_main_region_Step3_r2_Waiting_for_sugar_to_be_added();
			break;
		case main_region_Step3_r2_Sugar_or_mapple_syrup:
			exitSequence_main_region_Step3_r2_Sugar_or_mapple_syrup();
			break;
		case main_region_Step3_r2_waiting_fo_mapple_syrup:
			exitSequence_main_region_Step3_r2_waiting_fo_mapple_syrup();
			break;
		case main_region_Step3_r2_End_option:
			exitSequence_main_region_Step3_r2_End_option();
			break;
		default:
			break;
		}
		
		switch (stateVector[2]) {
		case main_region_Step2_r2_ExpressoCase_r2_WaitWater:
			exitSequence_main_region_Step2_r2_ExpressoCase_r2_WaitWater();
			break;
		default:
			break;
		}
	}
	
	/* Default exit sequence for region r1 */
	private void exitSequence_main_region_Step1_r1() {
		switch (stateVector[0]) {
		case main_region_Step1_r1_Water_heat:
			exitSequence_main_region_Step1_r1_Water_heat();
			break;
		default:
			break;
		}
	}
	
	/* Default exit sequence for region r2 */
	private void exitSequence_main_region_Step1_r2() {
		switch (stateVector[1]) {
		case main_region_Step1_r2_First_step:
			exitSequence_main_region_Step1_r2_First_step();
			break;
		case main_region_Step1_r2_Drink_difference:
			exitSequence_main_region_Step1_r2_Drink_difference();
			break;
		default:
			break;
		}
	}
	
	/* Default exit sequence for region r1 */
	private void exitSequence_main_region_Step2_r1() {
		switch (stateVector[0]) {
		case main_region_Step2_r1_Cup_Placement:
			exitSequence_main_region_Step2_r1_Cup_Placement();
			break;
		case main_region_Step2_r1_Cup_placed:
			exitSequence_main_region_Step2_r1_Cup_placed();
			break;
		default:
			break;
		}
	}
	
	/* Default exit sequence for region r2 */
	private void exitSequence_main_region_Step2_r2() {
		switch (stateVector[1]) {
		case main_region_Step2_r2_Drink_difference_step2:
			exitSequence_main_region_Step2_r2_Drink_difference_step2();
			break;
		case main_region_Step2_r2_ExpressoCase_r1_PackSeed:
			exitSequence_main_region_Step2_r2_ExpressoCase_r1_PackSeed();
			break;
		case main_region_Step2_r2_Waiting_for_water_to_heat:
			exitSequence_main_region_Step2_r2_Waiting_for_water_to_heat();
			break;
		default:
			break;
		}
		
		switch (stateVector[2]) {
		case main_region_Step2_r2_ExpressoCase_r2_WaitWater:
			exitSequence_main_region_Step2_r2_ExpressoCase_r2_WaitWater();
			break;
		default:
			break;
		}
	}
	
	/* Default exit sequence for region r1 */
	private void exitSequence_main_region_Step2_r2_ExpressoCase_r1() {
		switch (stateVector[1]) {
		case main_region_Step2_r2_ExpressoCase_r1_PackSeed:
			exitSequence_main_region_Step2_r2_ExpressoCase_r1_PackSeed();
			break;
		default:
			break;
		}
	}
	
	/* Default exit sequence for region r2 */
	private void exitSequence_main_region_Step2_r2_ExpressoCase_r2() {
		switch (stateVector[2]) {
		case main_region_Step2_r2_ExpressoCase_r2_WaitWater:
			exitSequence_main_region_Step2_r2_ExpressoCase_r2_WaitWater();
			break;
		default:
			break;
		}
	}
	
	/* Default exit sequence for region r1 */
	private void exitSequence_main_region_Step3_r1() {
		switch (stateVector[0]) {
		case main_region_Step3_r1_Waiting_for_water_to_be_poured:
			exitSequence_main_region_Step3_r1_Waiting_for_water_to_be_poured();
			break;
		case main_region_Step3_r1_WaterPoured:
			exitSequence_main_region_Step3_r1_WaterPoured();
			break;
		default:
			break;
		}
	}
	
	/* Default exit sequence for region r2 */
	private void exitSequence_main_region_Step3_r2() {
		switch (stateVector[1]) {
		case main_region_Step3_r2_Milk_option__:
			exitSequence_main_region_Step3_r2_Milk_option__();
			break;
		case main_region_Step3_r2_Waiting_for_milk_to_be_poured:
			exitSequence_main_region_Step3_r2_Waiting_for_milk_to_be_poured();
			break;
		case main_region_Step3_r2_Waiting_for_sugar_to_be_added:
			exitSequence_main_region_Step3_r2_Waiting_for_sugar_to_be_added();
			break;
		case main_region_Step3_r2_Sugar_or_mapple_syrup:
			exitSequence_main_region_Step3_r2_Sugar_or_mapple_syrup();
			break;
		case main_region_Step3_r2_waiting_fo_mapple_syrup:
			exitSequence_main_region_Step3_r2_waiting_fo_mapple_syrup();
			break;
		case main_region_Step3_r2_End_option:
			exitSequence_main_region_Step3_r2_End_option();
			break;
		default:
			break;
		}
	}
	
	/* Default exit sequence for region r1 */
	private void exitSequence_main_region_Choice_and_payment_r1() {
		switch (stateVector[0]) {
		case main_region_Choice_and_payment_r1_No_drink_selected:
			exitSequence_main_region_Choice_and_payment_r1_No_drink_selected();
			break;
		case main_region_Choice_and_payment_r1_Drink_selected____not_enough_money_inserted:
			exitSequence_main_region_Choice_and_payment_r1_Drink_selected____not_enough_money_inserted();
			break;
		case main_region_Choice_and_payment_r1_Option_selected:
			exitSequence_main_region_Choice_and_payment_r1_Option_selected();
			break;
		default:
			break;
		}
	}
	
	/* Default react sequence for initial entry  */
	private void react_main_region_Step1_r1__entry_Default() {
		enterSequence_main_region_Step1_r1_Water_heat_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react_main_region_Step1_r2__entry_Default() {
		enterSequence_main_region_Step1_r2_Drink_difference_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react_main_region_Step2_r1__entry_Default() {
		enterSequence_main_region_Step2_r1_Cup_Placement_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react_main_region_Step2_r2__entry_Default() {
		enterSequence_main_region_Step2_r2_Drink_difference_step2_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react_main_region_Step2_r2_ExpressoCase_r1__entry_Default() {
		enterSequence_main_region_Step2_r2_ExpressoCase_r1_PackSeed_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react_main_region_Step2_r2_ExpressoCase_r2__entry_Default() {
		enterSequence_main_region_Step2_r2_ExpressoCase_r2_WaitWater_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react_main_region_Step3_r1__entry_Default() {
		enterSequence_main_region_Step3_r1_Waiting_for_water_to_be_poured_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react_main_region_Step3_r2__entry_Default() {
		enterSequence_main_region_Step3_r2_Sugar_or_mapple_syrup_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react_main_region__entry_Default() {
		enterSequence_main_region_CheckIngredients_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react_main_region_Choice_and_payment_r1__entry_Default() {
		enterSequence_main_region_Choice_and_payment_r1_No_drink_selected_default();
	}
	
	/* Default react sequence for deep history entry history */
	private void react_main_region_Choice_and_payment_r1_history() {
		/* Enter the region with deep history */
		if (historyVector[0] != State.$NullState$) {
			deepEnterSequence_main_region_Choice_and_payment_r1();
		} else {
			enterSequence_main_region_Choice_and_payment_r1_No_drink_selected_default();
		}
	}
	
	/* The reactions of state null. */
	private void react_main_region_Step2_r2__sync0() {
		enterSequence_main_region_Step2_r2_Waiting_for_water_to_heat_default();
	}
	
	/* The reactions of state null. */
	private void react_main_region__sync0() {
		enterSequence_main_region_Step3_default();
	}
	
	/* The reactions of state null. */
	private void react_main_region__sync1() {
		enterSequence_main_region_Step2_default();
	}
	
	/* The reactions of state null. */
	private void react_main_region__sync2() {
		enterSequence_main_region_Drink_difference_default();
	}
	
	/* The reactions of state null. */
	private void react_main_region__sync3() {
		enterSequence_main_region_Drink_difference_default();
	}
	
	private boolean react() {
		return false;
	}
	
	private boolean main_region_Step1_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			did_transition = false;
		}
		if (did_transition==false) {
			did_transition = react();
		}
		return did_transition;
	}
	
	private boolean main_region_Step1_r1_Water_heat_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (((true && isStateActive(State.main_region_Step1_r2_First_step)) && sCInterface.step1ElementPlaced)) {
				exitSequence_main_region_Step1();
				react_main_region__sync1();
			} else {
				did_transition = false;
			}
		}
		return did_transition;
	}
	
	private boolean main_region_Step1_r2_First_step_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (((sCInterface.step1ElementPlaced && isStateActive(State.main_region_Step1_r1_Water_heat)) && true)) {
				exitSequence_main_region_Step1();
				react_main_region__sync1();
			} else {
				did_transition = false;
			}
		}
		if (did_transition==false) {
			did_transition = main_region_Step1_react(try_transition);
		}
		return did_transition;
	}
	
	private boolean main_region_Step1_r2_Drink_difference_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (sCInterface.podPlacement) {
				exitSequence_main_region_Step1_r2_Drink_difference();
				sCInterface.raisePodPlacing();
				
				enterSequence_main_region_Step1_r2_First_step_default();
				main_region_Step1_react(false);
			} else {
				if (sCInterface.seedGrind) {
					exitSequence_main_region_Step1_r2_Drink_difference();
					sCInterface.raiseSeedGrinding();
					
					enterSequence_main_region_Step1_r2_First_step_default();
					main_region_Step1_react(false);
				} else {
					if (sCInterface.bagPlacement) {
						exitSequence_main_region_Step1_r2_Drink_difference();
						sCInterface.raiseBagPlacing();
						
						enterSequence_main_region_Step1_r2_First_step_default();
						main_region_Step1_react(false);
					} else {
						did_transition = false;
					}
				}
			}
		}
		if (did_transition==false) {
			did_transition = main_region_Step1_react(try_transition);
		}
		return did_transition;
	}
	
	private boolean main_region_Step2_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			did_transition = false;
		}
		if (did_transition==false) {
			did_transition = react();
		}
		return did_transition;
	}
	
	private boolean main_region_Step2_r1_Cup_Placement_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (timeEvents[0]) {
				exitSequence_main_region_Step2_r1_Cup_Placement();
				enterSequence_main_region_Step2_r1_Cup_placed_default();
			} else {
				did_transition = false;
			}
		}
		return did_transition;
	}
	
	private boolean main_region_Step2_r1_Cup_placed_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (((true && isStateActive(State.main_region_Step2_r2_Waiting_for_water_to_heat)) && sCInterface.waterHeated)) {
				exitSequence_main_region_Step2();
				react_main_region__sync0();
			} else {
				did_transition = false;
			}
		}
		return did_transition;
	}
	
	private boolean main_region_Step2_r2_Drink_difference_step2_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (sCInterface.waitingForWater) {
				exitSequence_main_region_Step2_r2_Drink_difference_step2();
				sCInterface.raiseWaitForWaterHeated();
				
				enterSequence_main_region_Step2_r2_Waiting_for_water_to_heat_default();
				main_region_Step2_react(false);
			} else {
				if (sCInterface.step2Expresso) {
					exitSequence_main_region_Step2_r2_Drink_difference_step2();
					enterSequence_main_region_Step2_r2_ExpressoCase_default();
					main_region_Step2_react(false);
				} else {
					did_transition = false;
				}
			}
		}
		if (did_transition==false) {
			did_transition = main_region_Step2_react(try_transition);
		}
		return did_transition;
	}
	
	private boolean main_region_Step2_r2_ExpressoCase_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			did_transition = false;
		}
		if (did_transition==false) {
			did_transition = main_region_Step2_react(try_transition);
		}
		return did_transition;
	}
	
	private boolean main_region_Step2_r2_ExpressoCase_r1_PackSeed_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (((sCInterface.endPackSeed && isStateActive(State.main_region_Step2_r2_ExpressoCase_r2_WaitWater)) && true)) {
				exitSequence_main_region_Step2_r2_ExpressoCase();
				react_main_region_Step2_r2__sync0();
			} else {
				did_transition = false;
			}
		}
		return did_transition;
	}
	
	private boolean main_region_Step2_r2_ExpressoCase_r2_WaitWater_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (((true && isStateActive(State.main_region_Step2_r2_ExpressoCase_r1_PackSeed)) && sCInterface.endPackSeed)) {
				exitSequence_main_region_Step2_r2_ExpressoCase();
				react_main_region_Step2_r2__sync0();
			} else {
				did_transition = false;
			}
		}
		if (did_transition==false) {
			did_transition = main_region_Step2_r2_ExpressoCase_react(try_transition);
		}
		return did_transition;
	}
	
	private boolean main_region_Step2_r2_Waiting_for_water_to_heat_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (((sCInterface.waterHeated && isStateActive(State.main_region_Step2_r1_Cup_placed)) && true)) {
				exitSequence_main_region_Step2();
				react_main_region__sync0();
			} else {
				did_transition = false;
			}
		}
		if (did_transition==false) {
			did_transition = main_region_Step2_react(try_transition);
		}
		return did_transition;
	}
	
	private boolean main_region_Step3_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			did_transition = false;
		}
		if (did_transition==false) {
			did_transition = react();
		}
		return did_transition;
	}
	
	private boolean main_region_Step3_r1_Waiting_for_water_to_be_poured_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (sCInterface.waterPoured) {
				exitSequence_main_region_Step3_r1_Waiting_for_water_to_be_poured();
				enterSequence_main_region_Step3_r1_WaterPoured_default();
			} else {
				did_transition = false;
			}
		}
		return did_transition;
	}
	
	private boolean main_region_Step3_r1_WaterPoured_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (((true && isStateActive(State.main_region_Step3_r2_End_option)) && true)) {
				exitSequence_main_region_Step3();
				react_main_region__sync2();
			} else {
				if (((true && isStateActive(State.main_region_Step3_r2_End_option)) && true)) {
					exitSequence_main_region_Step3();
					react_main_region__sync3();
				} else {
					did_transition = false;
				}
			}
		}
		return did_transition;
	}
	
	private boolean main_region_Step3_r2_Milk_option___react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (sCInterface.noMilkOption) {
				exitSequence_main_region_Step3_r2_Milk_option__();
				enterSequence_main_region_Step3_r2_End_option_default();
				main_region_Step3_react(false);
			} else {
				if (sCInterface.milkOption) {
					exitSequence_main_region_Step3_r2_Milk_option__();
					enterSequence_main_region_Step3_r2_Waiting_for_milk_to_be_poured_default();
					main_region_Step3_react(false);
				} else {
					did_transition = false;
				}
			}
		}
		if (did_transition==false) {
			did_transition = main_region_Step3_react(try_transition);
		}
		return did_transition;
	}
	
	private boolean main_region_Step3_r2_Waiting_for_milk_to_be_poured_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (sCInterface.milkAdded) {
				exitSequence_main_region_Step3_r2_Waiting_for_milk_to_be_poured();
				enterSequence_main_region_Step3_r2_End_option_default();
				main_region_Step3_react(false);
			} else {
				did_transition = false;
			}
		}
		if (did_transition==false) {
			did_transition = main_region_Step3_react(try_transition);
		}
		return did_transition;
	}
	
	private boolean main_region_Step3_r2_Waiting_for_sugar_to_be_added_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (sCInterface.sugarAdded) {
				exitSequence_main_region_Step3_r2_Waiting_for_sugar_to_be_added();
				enterSequence_main_region_Step3_r2_Milk_option___default();
				main_region_Step3_react(false);
			} else {
				did_transition = false;
			}
		}
		if (did_transition==false) {
			did_transition = main_region_Step3_react(try_transition);
		}
		return did_transition;
	}
	
	private boolean main_region_Step3_r2_Sugar_or_mapple_syrup_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (sCInterface.sugar) {
				exitSequence_main_region_Step3_r2_Sugar_or_mapple_syrup();
				enterSequence_main_region_Step3_r2_Waiting_for_sugar_to_be_added_default();
				main_region_Step3_react(false);
			} else {
				if (sCInterface.syrup) {
					exitSequence_main_region_Step3_r2_Sugar_or_mapple_syrup();
					enterSequence_main_region_Step3_r2_waiting_fo_mapple_syrup_default();
					main_region_Step3_react(false);
				} else {
					did_transition = false;
				}
			}
		}
		if (did_transition==false) {
			did_transition = main_region_Step3_react(try_transition);
		}
		return did_transition;
	}
	
	private boolean main_region_Step3_r2_waiting_fo_mapple_syrup_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (sCInterface.syrupAdded) {
				exitSequence_main_region_Step3_r2_waiting_fo_mapple_syrup();
				enterSequence_main_region_Step3_r2_Milk_option___default();
				main_region_Step3_react(false);
			} else {
				did_transition = false;
			}
		}
		if (did_transition==false) {
			did_transition = main_region_Step3_react(try_transition);
		}
		return did_transition;
	}
	
	private boolean main_region_Step3_r2_End_option_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (((true && isStateActive(State.main_region_Step3_r1_WaterPoured)) && true)) {
				exitSequence_main_region_Step3();
				react_main_region__sync2();
			} else {
				if (((true && isStateActive(State.main_region_Step3_r1_WaterPoured)) && true)) {
					exitSequence_main_region_Step3();
					react_main_region__sync3();
				} else {
					did_transition = false;
				}
			}
		}
		if (did_transition==false) {
			did_transition = main_region_Step3_react(try_transition);
		}
		return did_transition;
	}
	
	private boolean main_region_Choice_and_payment_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (sCInterface.insertCoin10) {
				exitSequence_main_region_Choice_and_payment();
				sCInterface.raiseCoin10Inserted();
				
				entryAction_main_region_Choice_and_payment();
				react_main_region_Choice_and_payment_r1_history();
			} else {
				if (sCInterface.cancelButton) {
					exitSequence_main_region_Choice_and_payment();
					sCInterface.raiseCancel();
					
					entryAction_main_region_Choice_and_payment();
					enterSequence_main_region_Choice_and_payment_r1_No_drink_selected_default();
					react();
				} else {
					if (sCInterface.enoughMoneyInserted) {
						exitSequence_main_region_Choice_and_payment();
						sCInterface.raiseDoTransaction();
						
						enterSequence_main_region_Step1_default();
						react();
					} else {
						if (sCInterface.teaButton) {
							exitSequence_main_region_Choice_and_payment();
							sCInterface.raiseTeaChosed();
							
							entryAction_main_region_Choice_and_payment();
							enterSequence_main_region_Choice_and_payment_r1_Drink_selected____not_enough_money_inserted_default();
							react();
						} else {
							if (sCInterface.expressoButton) {
								exitSequence_main_region_Choice_and_payment();
								sCInterface.raiseExpressoChosed();
								
								entryAction_main_region_Choice_and_payment();
								enterSequence_main_region_Choice_and_payment_r1_Drink_selected____not_enough_money_inserted_default();
								react();
							} else {
								if (sCInterface.coffeeButton) {
									exitSequence_main_region_Choice_and_payment();
									sCInterface.raiseCoffeeChosed();
									
									entryAction_main_region_Choice_and_payment();
									enterSequence_main_region_Choice_and_payment_r1_Drink_selected____not_enough_money_inserted_default();
									react();
								} else {
									if (sCInterface.milkButton) {
										exitSequence_main_region_Choice_and_payment();
										sCInterface.raiseMilkChosed();
										
										entryAction_main_region_Choice_and_payment();
										enterSequence_main_region_Choice_and_payment_r1_Option_selected_default();
										react();
									} else {
										if (sCInterface.crustButton) {
											exitSequence_main_region_Choice_and_payment();
											sCInterface.raiseCrustChosed();
											
											entryAction_main_region_Choice_and_payment();
											enterSequence_main_region_Choice_and_payment_r1_Option_selected_default();
											react();
										} else {
											if (sCInterface.vanillaButton) {
												exitSequence_main_region_Choice_and_payment();
												sCInterface.raiseVanillaChosed();
												
												entryAction_main_region_Choice_and_payment();
												enterSequence_main_region_Choice_and_payment_r1_Option_selected_default();
												react();
											} else {
												if (sCInterface.syrupButton) {
													exitSequence_main_region_Choice_and_payment();
													sCInterface.raiseSyrupChosed();
													
													entryAction_main_region_Choice_and_payment();
													enterSequence_main_region_Choice_and_payment_r1_Option_selected_default();
													react();
												} else {
													if (sCInterface.insertCoin25) {
														exitSequence_main_region_Choice_and_payment();
														sCInterface.raiseCoin25Inserted();
														
														entryAction_main_region_Choice_and_payment();
														react_main_region_Choice_and_payment_r1_history();
													} else {
														if (sCInterface.insertCoin50) {
															exitSequence_main_region_Choice_and_payment();
															sCInterface.raiseCoin50Inserted();
															
															entryAction_main_region_Choice_and_payment();
															react_main_region_Choice_and_payment_r1_history();
														} else {
															if (sCInterface.optionButton) {
																exitSequence_main_region_Choice_and_payment();
																entryAction_main_region_Choice_and_payment();
																react_main_region_Choice_and_payment_r1_history();
															} else {
																if (sCInterface.nFC) {
																	exitSequence_main_region_Choice_and_payment();
																	sCInterface.raiseNFCPayment();
																	
																	entryAction_main_region_Choice_and_payment();
																	react_main_region_Choice_and_payment_r1_history();
																} else {
																	if (timeEvents[1]) {
																		exitSequence_main_region_Choice_and_payment();
																		sCInterface.raiseAutomaticCancel();
																		
																		entryAction_main_region_Choice_and_payment();
																		enterSequence_main_region_Choice_and_payment_r1_No_drink_selected_default();
																		react();
																	} else {
																		did_transition = false;
																	}
																}
															}
														}
													}
												}
											}
										}
									}
								}
							}
						}
					}
				}
			}
		}
		if (did_transition==false) {
			did_transition = react();
		}
		return did_transition;
	}
	
	private boolean main_region_Choice_and_payment_r1_No_drink_selected_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			did_transition = false;
		}
		if (did_transition==false) {
			did_transition = main_region_Choice_and_payment_react(try_transition);
		}
		return did_transition;
	}
	
	private boolean main_region_Choice_and_payment_r1_Drink_selected____not_enough_money_inserted_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			did_transition = false;
		}
		if (did_transition==false) {
			did_transition = main_region_Choice_and_payment_react(try_transition);
		}
		return did_transition;
	}
	
	private boolean main_region_Choice_and_payment_r1_Option_selected_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			did_transition = false;
		}
		if (did_transition==false) {
			did_transition = main_region_Choice_and_payment_react(try_transition);
		}
		return did_transition;
	}
	
	private boolean main_region_WaitForCupToBeTaken_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (sCInterface.cupIsTaken) {
				exitSequence_main_region_WaitForCupToBeTaken();
				enterSequence_main_region_CleanMachine_default();
				react();
			} else {
				did_transition = false;
			}
		}
		if (did_transition==false) {
			did_transition = react();
		}
		return did_transition;
	}
	
	private boolean main_region_CleanMachine_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (timeEvents[2]) {
				exitSequence_main_region_CleanMachine();
				enterSequence_main_region_CheckIngredients_default();
				react();
			} else {
				did_transition = false;
			}
		}
		if (did_transition==false) {
			did_transition = react();
		}
		return did_transition;
	}
	
	private boolean main_region_Infusing_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (sCInterface.giveCup) {
				exitSequence_main_region_Infusing();
				enterSequence_main_region_WaitForCupToBeTaken_default();
				react();
			} else {
				did_transition = false;
			}
		}
		if (did_transition==false) {
			did_transition = react();
		}
		return did_transition;
	}
	
	private boolean main_region_CheckIngredients_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (timeEvents[3]) {
				exitSequence_main_region_CheckIngredients();
				sCInterface.raiseDisableMissingIngredients();
				
				enterSequence_main_region_Choice_and_payment_default();
				react();
			} else {
				did_transition = false;
			}
		}
		if (did_transition==false) {
			did_transition = react();
		}
		return did_transition;
	}
	
	private boolean main_region_Drink_difference_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (sCInterface.giveCup) {
				exitSequence_main_region_Drink_difference();
				enterSequence_main_region_WaitForCupToBeTaken_default();
				react();
			} else {
				if (sCInterface.letInfuse) {
					exitSequence_main_region_Drink_difference();
					enterSequence_main_region_Infusing_default();
					react();
				} else {
					did_transition = false;
				}
			}
		}
		if (did_transition==false) {
			did_transition = react();
		}
		return did_transition;
	}
	
}
