/** Generated by YAKINDU Statechart Tools code generator. */
package fr.univcotedazur.polytech.si4.fsm.2020.project.mvp;

import fr.univcotedazur.polytech.si4.fsm.2020.project.IStatemachine;
import fr.univcotedazur.polytech.si4.fsm.2020.project.ITimerCallback;
import java.util.LinkedList;
import java.util.List;
import java.util.Queue;
import java.util.concurrent.BlockingQueue;
import java.util.concurrent.LinkedBlockingQueue;

public interface IMVPStatemachine extends ITimerCallback,IStatemachine {
	public interface SCInterface {
	
		public void raiseCoffeeButton();
		
		public void raiseTeaButton();
		
		public void raiseExpressoButton();
		
		public void raiseCancelButton();
		
		public void raiseInsertCoin10();
		
		public void raiseInsertCoin25();
		
		public void raiseInsertCoin50();
		
		public void raiseNFC();
		
		public void raiseEnoughMoneyInserted();
		
		public void raiseGobeletRecupere();
		
		public void raisePositionnerDosette();
		
		public boolean isRaisedCoffeeChosed();
		
		public boolean isRaisedTeaChosed();
		
		public boolean isRaisedExpressoChosed();
		
		public boolean isRaisedCoin10Inserted();
		
		public boolean isRaisedCoin25Inserted();
		
		public boolean isRaisedCoin50Inserted();
		
		public boolean isRaisedCancel();
		
		public boolean isRaisedNFCPayment();
		
		public boolean isRaisedNotHotEnough();
		
		public boolean isRaisedHotEnoughOut();
		
		public boolean isRaisedGiveBackMoney();
		
		public boolean isRaisedGobeletIsReady();
		
		public boolean isRaisedGobeletIsTaken();
		
		public boolean isRaisedDoTransaction();
		
		public boolean getSelected();
		
		public void setSelected(boolean value);
		
		public boolean getPayedEnough();
		
		public void setPayedEnough(boolean value);
		
		public boolean getHotEnough();
		
		public void setHotEnough(boolean value);
		
		public boolean getGobeletOk();
		
		public void setGobeletOk(boolean value);
		
		public boolean getGobeletTaken();
		
		public void setGobeletTaken(boolean value);
		
	public List<SCInterfaceListener> getListeners();
	}
	
	public interface SCInterfaceListener {
	
		public void onCoffeeChosedRaised();
		public void onTeaChosedRaised();
		public void onExpressoChosedRaised();
		public void onCoin10InsertedRaised();
		public void onCoin25InsertedRaised();
		public void onCoin50InsertedRaised();
		public void onCancelRaised();
		public void onNFCPaymentRaised();
		public void onNotHotEnoughRaised();
		public void onHotEnoughOutRaised();
		public void onGiveBackMoneyRaised();
		public void onGobeletIsReadyRaised();
		public void onGobeletIsTakenRaised();
		public void onDoTransactionRaised();
		}
	
	public SCInterface getSCInterface();
	
}
