/** Generated by YAKINDU Statechart Tools code generator. */
package fr.univcotedazur.polytech.si4.fsm.2020.project.mvp;

import fr.univcotedazur.polytech.si4.fsm.2020.project.ITimer;
import java.util.LinkedList;
import java.util.List;
import java.util.Queue;
import java.util.concurrent.BlockingQueue;
import java.util.concurrent.LinkedBlockingQueue;

public class MVPStatemachine implements IMVPStatemachine {
	protected class SCInterfaceImpl implements SCInterface {
	
		private List<SCInterfaceListener> listeners = new LinkedList<SCInterfaceListener>();
		
		public List<SCInterfaceListener> getListeners() {
			return listeners;
		}
		private boolean podPlacement;
		
		
		public void raisePodPlacement() {
			synchronized(MVPStatemachine.this) {
				inEventQueue.add(
					new Runnable() {
						@Override
						public void run() {
							podPlacement = true;
							singleCycle();
						}
					}
				);
				runCycle();
			}
		}
		
		private boolean coffeeButton;
		
		
		public void raiseCoffeeButton() {
			synchronized(MVPStatemachine.this) {
				inEventQueue.add(
					new Runnable() {
						@Override
						public void run() {
							coffeeButton = true;
							singleCycle();
						}
					}
				);
				runCycle();
			}
		}
		
		private boolean teaButton;
		
		
		public void raiseTeaButton() {
			synchronized(MVPStatemachine.this) {
				inEventQueue.add(
					new Runnable() {
						@Override
						public void run() {
							teaButton = true;
							singleCycle();
						}
					}
				);
				runCycle();
			}
		}
		
		private boolean expressoButton;
		
		
		public void raiseExpressoButton() {
			synchronized(MVPStatemachine.this) {
				inEventQueue.add(
					new Runnable() {
						@Override
						public void run() {
							expressoButton = true;
							singleCycle();
						}
					}
				);
				runCycle();
			}
		}
		
		private boolean cancelButton;
		
		
		public void raiseCancelButton() {
			synchronized(MVPStatemachine.this) {
				inEventQueue.add(
					new Runnable() {
						@Override
						public void run() {
							cancelButton = true;
							singleCycle();
						}
					}
				);
				runCycle();
			}
		}
		
		private boolean insertCoin10;
		
		
		public void raiseInsertCoin10() {
			synchronized(MVPStatemachine.this) {
				inEventQueue.add(
					new Runnable() {
						@Override
						public void run() {
							insertCoin10 = true;
							singleCycle();
						}
					}
				);
				runCycle();
			}
		}
		
		private boolean insertCoin25;
		
		
		public void raiseInsertCoin25() {
			synchronized(MVPStatemachine.this) {
				inEventQueue.add(
					new Runnable() {
						@Override
						public void run() {
							insertCoin25 = true;
							singleCycle();
						}
					}
				);
				runCycle();
			}
		}
		
		private boolean insertCoin50;
		
		
		public void raiseInsertCoin50() {
			synchronized(MVPStatemachine.this) {
				inEventQueue.add(
					new Runnable() {
						@Override
						public void run() {
							insertCoin50 = true;
							singleCycle();
						}
					}
				);
				runCycle();
			}
		}
		
		private boolean nFC;
		
		
		public void raiseNFC() {
			synchronized(MVPStatemachine.this) {
				inEventQueue.add(
					new Runnable() {
						@Override
						public void run() {
							nFC = true;
							singleCycle();
						}
					}
				);
				runCycle();
			}
		}
		
		private boolean enoughMoneyInserted;
		
		
		public void raiseEnoughMoneyInserted() {
			synchronized(MVPStatemachine.this) {
				inEventQueue.add(
					new Runnable() {
						@Override
						public void run() {
							enoughMoneyInserted = true;
							singleCycle();
						}
					}
				);
				runCycle();
			}
		}
		
		private boolean cupPickedUp;
		
		
		public void raiseCupPickedUp() {
			synchronized(MVPStatemachine.this) {
				inEventQueue.add(
					new Runnable() {
						@Override
						public void run() {
							cupPickedUp = true;
							singleCycle();
						}
					}
				);
				runCycle();
			}
		}
		
		private boolean positionnerDosette;
		
		
		public void raisePositionnerDosette() {
			synchronized(MVPStatemachine.this) {
				inEventQueue.add(
					new Runnable() {
						@Override
						public void run() {
							positionnerDosette = true;
							singleCycle();
						}
					}
				);
				runCycle();
			}
		}
		
<<<<<<< HEAD
		private boolean seedGrind;
		
		
		public void raiseSeedGrind() {
			synchronized(MVPStatemachine.this) {
				inEventQueue.add(
					new Runnable() {
						@Override
						public void run() {
							seedGrind = true;
							singleCycle();
						}
					}
				);
				runCycle();
			}
		}
		
		private boolean bagPlacement;
		
		
		public void raiseBagPlacement() {
			synchronized(MVPStatemachine.this) {
				inEventQueue.add(
					new Runnable() {
						@Override
						public void run() {
							bagPlacement = true;
							singleCycle();
						}
					}
				);
				runCycle();
			}
		}
		
		private boolean waitingForWater;
		
		
		public void raiseWaitingForWater() {
			synchronized(MVPStatemachine.this) {
				inEventQueue.add(
					new Runnable() {
						@Override
						public void run() {
							waitingForWater = true;
							singleCycle();
						}
					}
				);
				runCycle();
			}
		}
		
		private boolean seedPacking;
		
		
		public void raiseSeedPacking() {
			synchronized(MVPStatemachine.this) {
				inEventQueue.add(
					new Runnable() {
						@Override
						public void run() {
							seedPacking = true;
							singleCycle();
						}
					}
				);
				runCycle();
			}
		}
		
		private boolean endWaterHeat;
		
		
		public void raiseEndWaterHeat() {
			synchronized(MVPStatemachine.this) {
				inEventQueue.add(
					new Runnable() {
						@Override
						public void run() {
							endWaterHeat = true;
							singleCycle();
						}
					}
				);
				runCycle();
			}
		}
		
		private boolean addSugar;
		
		
		public boolean isRaisedAddSugar() {
			synchronized(MVPStatemachine.this) {
				return addSugar;
			}
		}
		
		protected void raiseAddSugar() {
			synchronized(MVPStatemachine.this) {
				addSugar = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onAddSugarRaised();
				}
			}
		}
		
		private boolean endFirstStep;
		
		
		public boolean isRaisedEndFirstStep() {
			synchronized(MVPStatemachine.this) {
				return endFirstStep;
			}
		}
		
		protected void raiseEndFirstStep() {
			synchronized(MVPStatemachine.this) {
				endFirstStep = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onEndFirstStepRaised();
				}
			}
		}
		
		private boolean endSecondStep;
		
		
		public boolean isRaisedEndSecondStep() {
			synchronized(MVPStatemachine.this) {
				return endSecondStep;
			}
		}
		
		protected void raiseEndSecondStep() {
			synchronized(MVPStatemachine.this) {
				endSecondStep = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onEndSecondStepRaised();
				}
			}
		}
		
		private boolean packSeed;
		
		
		public boolean isRaisedPackSeed() {
			synchronized(MVPStatemachine.this) {
				return packSeed;
			}
		}
		
		protected void raisePackSeed() {
			synchronized(MVPStatemachine.this) {
				packSeed = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onPackSeedRaised();
				}
			}
		}
		
		private boolean waitForWater;
=======
		private boolean cancel;
>>>>>>> 68d868c1c4efdf8a22dfb9d5b0c54d4297ed849b
		
		
		public boolean isRaisedWaitForWater() {
			synchronized(MVPStatemachine.this) {
				return waitForWater;
			}
		}
		
		protected void raiseWaitForWater() {
			synchronized(MVPStatemachine.this) {
				waitForWater = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onWaitForWaterRaised();
				}
			}
		}
		
<<<<<<< HEAD
		private boolean cupPlacement;
		
		
		public boolean isRaisedCupPlacement() {
			synchronized(MVPStatemachine.this) {
				return cupPlacement;
			}
		}
		
		protected void raiseCupPlacement() {
			synchronized(MVPStatemachine.this) {
				cupPlacement = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onCupPlacementRaised();
				}
			}
		}
		
		private boolean bagPlaced;
=======
		private boolean notHotEnough;
>>>>>>> 68d868c1c4efdf8a22dfb9d5b0c54d4297ed849b
		
		
		public boolean isRaisedBagPlaced() {
			synchronized(MVPStatemachine.this) {
				return bagPlaced;
			}
		}
		
		protected void raiseBagPlaced() {
			synchronized(MVPStatemachine.this) {
				bagPlaced = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onBagPlacedRaised();
				}
			}
		}
		
		private boolean seedGrinded;
		
		
		public boolean isRaisedSeedGrinded() {
			synchronized(MVPStatemachine.this) {
				return seedGrinded;
			}
		}
		
		protected void raiseSeedGrinded() {
			synchronized(MVPStatemachine.this) {
				seedGrinded = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onSeedGrindedRaised();
				}
			}
		}
		
		private boolean podPlaced;
		
		
		public boolean isRaisedPodPlaced() {
			synchronized(MVPStatemachine.this) {
				return podPlaced;
			}
		}
		
		protected void raisePodPlaced() {
			synchronized(MVPStatemachine.this) {
				podPlaced = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onPodPlacedRaised();
				}
			}
		}
		
		private boolean waterHeated;
		
		
		public boolean isRaisedWaterHeated() {
			synchronized(MVPStatemachine.this) {
				return waterHeated;
			}
		}
		
		protected void raiseWaterHeated() {
			synchronized(MVPStatemachine.this) {
				waterHeated = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onWaterHeatedRaised();
				}
			}
		}
		
		private boolean coffeeChosed;
		
		
		public boolean isRaisedCoffeeChosed() {
			synchronized(MVPStatemachine.this) {
				return coffeeChosed;
			}
		}
		
		protected void raiseCoffeeChosed() {
			synchronized(MVPStatemachine.this) {
				coffeeChosed = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onCoffeeChosedRaised();
				}
			}
		}
		
		private boolean teaChosed;
		
		
		public boolean isRaisedTeaChosed() {
			synchronized(MVPStatemachine.this) {
				return teaChosed;
			}
		}
		
		protected void raiseTeaChosed() {
			synchronized(MVPStatemachine.this) {
				teaChosed = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onTeaChosedRaised();
				}
			}
		}
		
		private boolean expressoChosed;
		
		
		public boolean isRaisedExpressoChosed() {
			synchronized(MVPStatemachine.this) {
				return expressoChosed;
			}
		}
		
		protected void raiseExpressoChosed() {
			synchronized(MVPStatemachine.this) {
				expressoChosed = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onExpressoChosedRaised();
				}
			}
		}
		
		private boolean coin10Inserted;
		
		
		public boolean isRaisedCoin10Inserted() {
			synchronized(MVPStatemachine.this) {
				return coin10Inserted;
			}
		}
		
		protected void raiseCoin10Inserted() {
			synchronized(MVPStatemachine.this) {
				coin10Inserted = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onCoin10InsertedRaised();
				}
			}
		}
		
		private boolean coin25Inserted;
		
		
		public boolean isRaisedCoin25Inserted() {
			synchronized(MVPStatemachine.this) {
				return coin25Inserted;
			}
		}
		
		protected void raiseCoin25Inserted() {
			synchronized(MVPStatemachine.this) {
				coin25Inserted = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onCoin25InsertedRaised();
				}
			}
		}
		
		private boolean coin50Inserted;
		
		
		public boolean isRaisedCoin50Inserted() {
			synchronized(MVPStatemachine.this) {
				return coin50Inserted;
			}
		}
		
		protected void raiseCoin50Inserted() {
			synchronized(MVPStatemachine.this) {
				coin50Inserted = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onCoin50InsertedRaised();
				}
			}
		}
		
		private boolean cancel;
		
		
		public boolean isRaisedCancel() {
			synchronized(MVPStatemachine.this) {
				return cancel;
			}
		}
		
		protected void raiseCancel() {
			synchronized(MVPStatemachine.this) {
				cancel = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onCancelRaised();
				}
			}
		}
		
		private boolean nFCPayment;
		
		
		public boolean isRaisedNFCPayment() {
			synchronized(MVPStatemachine.this) {
				return nFCPayment;
			}
		}
		
<<<<<<< HEAD
		protected void raiseNFCPayment() {
			synchronized(MVPStatemachine.this) {
				nFCPayment = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onNFCPaymentRaised();
				}
			}
=======
		cancel = false;
		notHotEnough = false;
		hotEnoughOut = false;
		giveBackMoney = false;
		gobeletIsReady = false;
		gobeletIsTaken = false;
		doTransaction = false;
>>>>>>> 68d868c1c4efdf8a22dfb9d5b0c54d4297ed849b
		}
		
		private boolean giveBackMoney;
		
		
		public boolean isRaisedGiveBackMoney() {
			synchronized(MVPStatemachine.this) {
				return giveBackMoney;
			}
		}
		
		protected void raiseGiveBackMoney() {
			synchronized(MVPStatemachine.this) {
				giveBackMoney = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onGiveBackMoneyRaised();
				}
			}
		}
		
		private boolean doTransaction;
		
		
		public boolean isRaisedDoTransaction() {
			synchronized(MVPStatemachine.this) {
				return doTransaction;
			}
		}
		
		protected void raiseDoTransaction() {
			synchronized(MVPStatemachine.this) {
				doTransaction = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onDoTransactionRaised();
				}
			}
		}
		
		private boolean selected;
		
		public synchronized boolean getSelected() {
			synchronized(MVPStatemachine.this) {
				return selected;
			}
		}
		
		public void setSelected(boolean value) {
			synchronized(MVPStatemachine.this) {
				this.selected = value;
			}
		}
		
		private boolean payedEnough;
		
		public synchronized boolean getPayedEnough() {
			synchronized(MVPStatemachine.this) {
				return payedEnough;
			}
		}
		
		public void setPayedEnough(boolean value) {
			synchronized(MVPStatemachine.this) {
				this.payedEnough = value;
			}
		}
		
		private boolean hotEnough;
		
		public synchronized boolean getHotEnough() {
			synchronized(MVPStatemachine.this) {
				return hotEnough;
			}
		}
		
		public void setHotEnough(boolean value) {
			synchronized(MVPStatemachine.this) {
				this.hotEnough = value;
			}
		}
		
		private boolean gobeletOk;
		
		public synchronized boolean getGobeletOk() {
			synchronized(MVPStatemachine.this) {
				return gobeletOk;
			}
		}
		
		public void setGobeletOk(boolean value) {
			synchronized(MVPStatemachine.this) {
				this.gobeletOk = value;
			}
		}
		
		private boolean gobeletTaken;
		
		public synchronized boolean getGobeletTaken() {
			synchronized(MVPStatemachine.this) {
				return gobeletTaken;
			}
		}
		
		public void setGobeletTaken(boolean value) {
			synchronized(MVPStatemachine.this) {
				this.gobeletTaken = value;
			}
		}
		
		protected void clearEvents() {
			podPlacement = false;
			coffeeButton = false;
			teaButton = false;
			expressoButton = false;
			cancelButton = false;
			insertCoin10 = false;
			insertCoin25 = false;
			insertCoin50 = false;
			nFC = false;
			enoughMoneyInserted = false;
			cupPickedUp = false;
			positionnerDosette = false;
			seedGrind = false;
			bagPlacement = false;
			waitingForWater = false;
			seedPacking = false;
			endWaterHeat = false;
		}
		protected void clearOutEvents() {
		
		addSugar = false;
		endFirstStep = false;
		endSecondStep = false;
		packSeed = false;
		waitForWater = false;
		cupPlacement = false;
		bagPlaced = false;
		seedGrinded = false;
		podPlaced = false;
		waterHeated = false;
		coffeeChosed = false;
		teaChosed = false;
		expressoChosed = false;
		coin10Inserted = false;
		coin25Inserted = false;
		coin50Inserted = false;
		cancel = false;
		nFCPayment = false;
		giveBackMoney = false;
		doTransaction = false;
		}
		
	}
	
	
	protected SCInterfaceImpl sCInterface;
	
	private boolean initialized = false;
	
	public enum State {
		main_region_Choice_and_Payment,
		main_region_Choice_and_Payment_Choice_region_Chosed_or_not,
		main_region_Choice_and_Payment_Choice_region_Chosed_or_not_r1_Drink_chosed,
		main_region_Choice_and_Payment_Choice_region_Chosed_or_not_r1_No_choice,
		main_region_Choice_and_Payment_Payment_region_Payed_or_not,
		main_region_Choice_and_Payment_Payment_region_Payed_or_not_r1_No_money,
		main_region_Choice_and_Payment_Payment_region_Payed_or_not_r1_Money_inserted,
		main_region_Choice_and_Payment_Payment_region_Payed_or_not_r1_Enough_money,
<<<<<<< HEAD
		main_region_Step1,
		main_region_Step1_r1_Water_heat,
		main_region_Step1_r1__final_,
		main_region_Step1_r2_First_step,
		main_region_Step1_r2_Drink_difference,
		main_region_Step1_r2__final_,
		main_region_Step2,
		main_region_Step2_r1_Cup_Placement,
		main_region_Step2_r2_Drink_difference,
		main_region_Step2_r2_Second_step,
		main_region_Step3,
		main_region_Step3_r1_Water_wait,
		main_region_Step3_r2_Sugar_added,
=======
		main_region_Fin_de_la_commande,
		main_region_Fin_de_la_commande_nettoyage_Nettoyage,
		main_region_Fin_de_la_commande_fin_de_la_commande_rendu_monnaie_Rendre_monnaie,
		main_region_Fin_de_la_commande_R_cup_rer_gobelet_Gobelet_pret,
		main_region_Fin_de_la_commande_R_cup_rer_gobelet_Gobelet_r_cup_r_,
		main_region_Preparation_de_la_boisson,
		main_region_Preparation_de_la_boisson_gobelet_Positionnement_dosette,
		main_region_Preparation_de_la_boisson_gobelet_Positionnement_gobelet,
		main_region_Preparation_de_la_boisson_gobelet_Ajout_du_sucre,
		main_region_Preparation_de_la_boisson_eau_Chauffage,
		main_region_Preparation_de_la_boisson_eau_AssezChauff_,
		main_region_Preparation_de_la_boisson_eau_Versement_de_l_eau,
		main_region_End,
>>>>>>> 68d868c1c4efdf8a22dfb9d5b0c54d4297ed849b
		$NullState$
	};
	
	private State[] historyVector = new State[2];
	private final State[] stateVector = new State[3];
	
	private int nextStateIndex;
	
	private ITimer timer;
	
	private final boolean[] timeEvents = new boolean[6];
	
	private BlockingQueue<Runnable> inEventQueue = new LinkedBlockingQueue<Runnable>();
	private boolean isRunningCycle = false;
	public MVPStatemachine() {
		sCInterface = new SCInterfaceImpl();
	}
	
	public synchronized void init() {
		this.initialized = true;
		if (timer == null) {
			throw new IllegalStateException("timer not set.");
		}
		for (int i = 0; i < 3; i++) {
			stateVector[i] = State.$NullState$;
		}
		for (int i = 0; i < 2; i++) {
			historyVector[i] = State.$NullState$;
		}
		clearEvents();
		clearOutEvents();
		sCInterface.setSelected(false);
		
		sCInterface.setPayedEnough(false);
		
		sCInterface.setHotEnough(false);
		
		sCInterface.setGobeletOk(false);
		
		sCInterface.setGobeletTaken(false);
	}
	
	public synchronized void enter() {
		if (!initialized) {
			throw new IllegalStateException(
				"The state machine needs to be initialized first by calling the init() function."
			);
		}
		if (timer == null) {
			throw new IllegalStateException("timer not set.");
		}
		enterSequence_main_region_default();
	}
	
	public synchronized void runCycle() {
		if (!initialized)
			throw new IllegalStateException(
					"The state machine needs to be initialized first by calling the init() function.");
		
		if (isRunningCycle) {
			return;
		}
		isRunningCycle = true;
		
		clearOutEvents();
	
		Runnable task = getNextEvent();
		if (task == null) {
			task = getDefaultEvent();
		}
		
		while (task != null) {
			task.run();
			clearEvents();
			task = getNextEvent();
		}
		
		isRunningCycle = false;
	}
	
	protected synchronized void singleCycle() {
		for (nextStateIndex = 0; nextStateIndex < stateVector.length; nextStateIndex++) {
			switch (stateVector[nextStateIndex]) {
				case main_region_Choice_and_Payment_Choice_region_Chosed_or_not_r1_Drink_chosed:
					main_region_Choice_and_Payment_Choice_region_Chosed_or_not_r1_Drink_chosed_react(true);
					break;
				case main_region_Choice_and_Payment_Choice_region_Chosed_or_not_r1_No_choice:
					main_region_Choice_and_Payment_Choice_region_Chosed_or_not_r1_No_choice_react(true);
					break;
				case main_region_Choice_and_Payment_Payment_region_Payed_or_not_r1_No_money:
					main_region_Choice_and_Payment_Payment_region_Payed_or_not_r1_No_money_react(true);
					break;
				case main_region_Choice_and_Payment_Payment_region_Payed_or_not_r1_Money_inserted:
					main_region_Choice_and_Payment_Payment_region_Payed_or_not_r1_Money_inserted_react(true);
					break;
				case main_region_Choice_and_Payment_Payment_region_Payed_or_not_r1_Enough_money:
					main_region_Choice_and_Payment_Payment_region_Payed_or_not_r1_Enough_money_react(true);
					break;
<<<<<<< HEAD
				case main_region_Step1_r1_Water_heat:
					main_region_Step1_r1_Water_heat_react(true);
					break;
				case main_region_Step1_r1__final_:
					main_region_Step1_r1__final__react(true);
					break;
				case main_region_Step1_r2_First_step:
					main_region_Step1_r2_First_step_react(true);
					break;
				case main_region_Step1_r2_Drink_difference:
					main_region_Step1_r2_Drink_difference_react(true);
					break;
				case main_region_Step1_r2__final_:
					main_region_Step1_r2__final__react(true);
					break;
				case main_region_Step2_r1_Cup_Placement:
					main_region_Step2_r1_Cup_Placement_react(true);
					break;
				case main_region_Step2_r2_Drink_difference:
					main_region_Step2_r2_Drink_difference_react(true);
					break;
				case main_region_Step2_r2_Second_step:
					main_region_Step2_r2_Second_step_react(true);
					break;
				case main_region_Step3_r1_Water_wait:
					main_region_Step3_r1_Water_wait_react(true);
					break;
				case main_region_Step3_r2_Sugar_added:
					main_region_Step3_r2_Sugar_added_react(true);
=======
				case main_region_Fin_de_la_commande_nettoyage_Nettoyage:
					main_region_Fin_de_la_commande_nettoyage_Nettoyage_react(true);
					break;
				case main_region_Fin_de_la_commande_fin_de_la_commande_rendu_monnaie_Rendre_monnaie:
					main_region_Fin_de_la_commande_fin_de_la_commande_rendu_monnaie_Rendre_monnaie_react(true);
					break;
				case main_region_Fin_de_la_commande_R_cup_rer_gobelet_Gobelet_pret:
					main_region_Fin_de_la_commande_R_cup_rer_gobelet_Gobelet_pret_react(true);
					break;
				case main_region_Fin_de_la_commande_R_cup_rer_gobelet_Gobelet_r_cup_r_:
					main_region_Fin_de_la_commande_R_cup_rer_gobelet_Gobelet_r_cup_r__react(true);
					break;
				case main_region_Preparation_de_la_boisson_gobelet_Positionnement_dosette:
					main_region_Preparation_de_la_boisson_gobelet_Positionnement_dosette_react(true);
					break;
				case main_region_Preparation_de_la_boisson_gobelet_Positionnement_gobelet:
					main_region_Preparation_de_la_boisson_gobelet_Positionnement_gobelet_react(true);
					break;
				case main_region_Preparation_de_la_boisson_gobelet_Ajout_du_sucre:
					main_region_Preparation_de_la_boisson_gobelet_Ajout_du_sucre_react(true);
					break;
				case main_region_Preparation_de_la_boisson_eau_Chauffage:
					main_region_Preparation_de_la_boisson_eau_Chauffage_react(true);
					break;
				case main_region_Preparation_de_la_boisson_eau_AssezChauff_:
					main_region_Preparation_de_la_boisson_eau_AssezChauff__react(true);
					break;
				case main_region_Preparation_de_la_boisson_eau_Versement_de_l_eau:
					main_region_Preparation_de_la_boisson_eau_Versement_de_l_eau_react(true);
					break;
				case main_region_End:
					main_region_End_react(true);
>>>>>>> 68d868c1c4efdf8a22dfb9d5b0c54d4297ed849b
					break;
			default:
				// $NullState$
			}
		}
	}
	
	protected Runnable getNextEvent() {
		if(!inEventQueue.isEmpty()) {
			return inEventQueue.poll();
		}
		return null;
	}
	
	protected Runnable getDefaultEvent() {
		return new Runnable() {
			@Override
			public void run() {
				singleCycle();
			}
		};
	}
	
	public synchronized void exit() {
		exitSequence_main_region();
	}
	
	/**
	 * @see IStatemachine#isActive()
	 */
	public synchronized boolean isActive() {
		return stateVector[0] != State.$NullState$||stateVector[1] != State.$NullState$||stateVector[2] != State.$NullState$;
	}
	
	/** 
	* @see IStatemachine#isFinal()
	*/
	public synchronized boolean isFinal() {
		return (stateVector[0] == State.main_region_Step1_r1__final_) && (stateVector[1] == State.main_region_Step1_r2__final_);
	}
	/**
	* This method resets the incoming events (time events included).
	*/
	protected void clearEvents() {
		sCInterface.clearEvents();
		for (int i=0; i<timeEvents.length; i++) {
			timeEvents[i] = false;
		}
	}
	
	/**
	* This method resets the outgoing events.
	*/
	protected void clearOutEvents() {
		sCInterface.clearOutEvents();
	}
	
	/**
	* Returns true if the given state is currently active otherwise false.
	*/
	public synchronized boolean isStateActive(State state) {
	
		switch (state) {
		case main_region_Choice_and_Payment:
			return stateVector[0].ordinal() >= State.
					main_region_Choice_and_Payment.ordinal()&& stateVector[0].ordinal() <= State.main_region_Choice_and_Payment_Payment_region_Payed_or_not_r1_Enough_money.ordinal();
		case main_region_Choice_and_Payment_Choice_region_Chosed_or_not:
			return stateVector[0].ordinal() >= State.
					main_region_Choice_and_Payment_Choice_region_Chosed_or_not.ordinal()&& stateVector[0].ordinal() <= State.main_region_Choice_and_Payment_Choice_region_Chosed_or_not_r1_No_choice.ordinal();
		case main_region_Choice_and_Payment_Choice_region_Chosed_or_not_r1_Drink_chosed:
			return stateVector[0] == State.main_region_Choice_and_Payment_Choice_region_Chosed_or_not_r1_Drink_chosed;
		case main_region_Choice_and_Payment_Choice_region_Chosed_or_not_r1_No_choice:
			return stateVector[0] == State.main_region_Choice_and_Payment_Choice_region_Chosed_or_not_r1_No_choice;
		case main_region_Choice_and_Payment_Payment_region_Payed_or_not:
			return stateVector[1].ordinal() >= State.
					main_region_Choice_and_Payment_Payment_region_Payed_or_not.ordinal()&& stateVector[1].ordinal() <= State.main_region_Choice_and_Payment_Payment_region_Payed_or_not_r1_Enough_money.ordinal();
		case main_region_Choice_and_Payment_Payment_region_Payed_or_not_r1_No_money:
			return stateVector[1] == State.main_region_Choice_and_Payment_Payment_region_Payed_or_not_r1_No_money;
		case main_region_Choice_and_Payment_Payment_region_Payed_or_not_r1_Money_inserted:
			return stateVector[1] == State.main_region_Choice_and_Payment_Payment_region_Payed_or_not_r1_Money_inserted;
		case main_region_Choice_and_Payment_Payment_region_Payed_or_not_r1_Enough_money:
			return stateVector[1] == State.main_region_Choice_and_Payment_Payment_region_Payed_or_not_r1_Enough_money;
<<<<<<< HEAD
		case main_region_Step1:
			return stateVector[0].ordinal() >= State.
					main_region_Step1.ordinal()&& stateVector[0].ordinal() <= State.main_region_Step1_r2__final_.ordinal();
		case main_region_Step1_r1_Water_heat:
			return stateVector[0] == State.main_region_Step1_r1_Water_heat;
		case main_region_Step1_r1__final_:
			return stateVector[0] == State.main_region_Step1_r1__final_;
		case main_region_Step1_r2_First_step:
			return stateVector[1] == State.main_region_Step1_r2_First_step;
		case main_region_Step1_r2_Drink_difference:
			return stateVector[1] == State.main_region_Step1_r2_Drink_difference;
		case main_region_Step1_r2__final_:
			return stateVector[1] == State.main_region_Step1_r2__final_;
		case main_region_Step2:
			return stateVector[0].ordinal() >= State.
					main_region_Step2.ordinal()&& stateVector[0].ordinal() <= State.main_region_Step2_r2_Second_step.ordinal();
		case main_region_Step2_r1_Cup_Placement:
			return stateVector[0] == State.main_region_Step2_r1_Cup_Placement;
		case main_region_Step2_r2_Drink_difference:
			return stateVector[1] == State.main_region_Step2_r2_Drink_difference;
		case main_region_Step2_r2_Second_step:
			return stateVector[1] == State.main_region_Step2_r2_Second_step;
		case main_region_Step3:
			return stateVector[0].ordinal() >= State.
					main_region_Step3.ordinal()&& stateVector[0].ordinal() <= State.main_region_Step3_r2_Sugar_added.ordinal();
		case main_region_Step3_r1_Water_wait:
			return stateVector[0] == State.main_region_Step3_r1_Water_wait;
		case main_region_Step3_r2_Sugar_added:
			return stateVector[1] == State.main_region_Step3_r2_Sugar_added;
=======
		case main_region_Fin_de_la_commande:
			return stateVector[0].ordinal() >= State.
					main_region_Fin_de_la_commande.ordinal()&& stateVector[0].ordinal() <= State.main_region_Fin_de_la_commande_R_cup_rer_gobelet_Gobelet_r_cup_r_.ordinal();
		case main_region_Fin_de_la_commande_nettoyage_Nettoyage:
			return stateVector[0] == State.main_region_Fin_de_la_commande_nettoyage_Nettoyage;
		case main_region_Fin_de_la_commande_fin_de_la_commande_rendu_monnaie_Rendre_monnaie:
			return stateVector[1] == State.main_region_Fin_de_la_commande_fin_de_la_commande_rendu_monnaie_Rendre_monnaie;
		case main_region_Fin_de_la_commande_R_cup_rer_gobelet_Gobelet_pret:
			return stateVector[2] == State.main_region_Fin_de_la_commande_R_cup_rer_gobelet_Gobelet_pret;
		case main_region_Fin_de_la_commande_R_cup_rer_gobelet_Gobelet_r_cup_r_:
			return stateVector[2] == State.main_region_Fin_de_la_commande_R_cup_rer_gobelet_Gobelet_r_cup_r_;
		case main_region_Preparation_de_la_boisson:
			return stateVector[0].ordinal() >= State.
					main_region_Preparation_de_la_boisson.ordinal()&& stateVector[0].ordinal() <= State.main_region_Preparation_de_la_boisson_eau_Versement_de_l_eau.ordinal();
		case main_region_Preparation_de_la_boisson_gobelet_Positionnement_dosette:
			return stateVector[0] == State.main_region_Preparation_de_la_boisson_gobelet_Positionnement_dosette;
		case main_region_Preparation_de_la_boisson_gobelet_Positionnement_gobelet:
			return stateVector[0] == State.main_region_Preparation_de_la_boisson_gobelet_Positionnement_gobelet;
		case main_region_Preparation_de_la_boisson_gobelet_Ajout_du_sucre:
			return stateVector[0] == State.main_region_Preparation_de_la_boisson_gobelet_Ajout_du_sucre;
		case main_region_Preparation_de_la_boisson_eau_Chauffage:
			return stateVector[1] == State.main_region_Preparation_de_la_boisson_eau_Chauffage;
		case main_region_Preparation_de_la_boisson_eau_AssezChauff_:
			return stateVector[1] == State.main_region_Preparation_de_la_boisson_eau_AssezChauff_;
		case main_region_Preparation_de_la_boisson_eau_Versement_de_l_eau:
			return stateVector[1] == State.main_region_Preparation_de_la_boisson_eau_Versement_de_l_eau;
		case main_region_End:
			return stateVector[0] == State.main_region_End;
>>>>>>> 68d868c1c4efdf8a22dfb9d5b0c54d4297ed849b
		default:
			return false;
		}
	}
	
	/**
	* Set the {@link ITimer} for the state machine. It must be set
	* externally on a timed state machine before a run cycle can be correctly
	* executed.
	* 
	* @param timer
	*/
	public synchronized void setTimer(ITimer timer) {
		this.timer = timer;
	}
	
	/**
	* Returns the currently used timer.
	* 
	* @return {@link ITimer}
	*/
	public ITimer getTimer() {
		return timer;
	}
	
	public synchronized void timeElapsed(int eventID) {
		inEventQueue.add(new Runnable() {
			@Override
			public void run() {
				timeEvents[eventID] = true;
				singleCycle();
			}
		});
		runCycle();
	}
	
	public SCInterface getSCInterface() {
		return sCInterface;
	}
	
	public synchronized void raisePodPlacement() {
		sCInterface.raisePodPlacement();
	}
	
	public synchronized void raiseCoffeeButton() {
		sCInterface.raiseCoffeeButton();
	}
	
	public synchronized void raiseTeaButton() {
		sCInterface.raiseTeaButton();
	}
	
	public synchronized void raiseExpressoButton() {
		sCInterface.raiseExpressoButton();
	}
	
	public synchronized void raiseCancelButton() {
		sCInterface.raiseCancelButton();
	}
	
	public synchronized void raiseInsertCoin10() {
		sCInterface.raiseInsertCoin10();
	}
	
	public synchronized void raiseInsertCoin25() {
		sCInterface.raiseInsertCoin25();
	}
	
	public synchronized void raiseInsertCoin50() {
		sCInterface.raiseInsertCoin50();
	}
	
	public synchronized void raiseNFC() {
		sCInterface.raiseNFC();
	}
	
	public synchronized void raiseEnoughMoneyInserted() {
		sCInterface.raiseEnoughMoneyInserted();
	}
	
	public synchronized void raiseCupPickedUp() {
		sCInterface.raiseCupPickedUp();
	}
	
	public synchronized void raisePositionnerDosette() {
		sCInterface.raisePositionnerDosette();
	}
	
<<<<<<< HEAD
	public synchronized void raiseSeedGrind() {
		sCInterface.raiseSeedGrind();
	}
	
	public synchronized void raiseBagPlacement() {
		sCInterface.raiseBagPlacement();
	}
	
	public synchronized void raiseWaitingForWater() {
		sCInterface.raiseWaitingForWater();
	}
	
	public synchronized void raiseSeedPacking() {
		sCInterface.raiseSeedPacking();
	}
	
	public synchronized void raiseEndWaterHeat() {
		sCInterface.raiseEndWaterHeat();
	}
	
	public synchronized boolean isRaisedAddSugar() {
		return sCInterface.isRaisedAddSugar();
	}
	
	public synchronized boolean isRaisedEndFirstStep() {
		return sCInterface.isRaisedEndFirstStep();
	}
	
	public synchronized boolean isRaisedEndSecondStep() {
		return sCInterface.isRaisedEndSecondStep();
	}
	
	public synchronized boolean isRaisedPackSeed() {
		return sCInterface.isRaisedPackSeed();
	}
	
	public synchronized boolean isRaisedWaitForWater() {
		return sCInterface.isRaisedWaitForWater();
	}
	
	public synchronized boolean isRaisedCupPlacement() {
		return sCInterface.isRaisedCupPlacement();
	}
	
	public synchronized boolean isRaisedBagPlaced() {
		return sCInterface.isRaisedBagPlaced();
	}
	
	public synchronized boolean isRaisedSeedGrinded() {
		return sCInterface.isRaisedSeedGrinded();
	}
	
	public synchronized boolean isRaisedPodPlaced() {
		return sCInterface.isRaisedPodPlaced();
	}
	
	public synchronized boolean isRaisedWaterHeated() {
		return sCInterface.isRaisedWaterHeated();
	}
	
	public synchronized boolean isRaisedCoffeeChosed() {
		return sCInterface.isRaisedCoffeeChosed();
	}
	
	public synchronized boolean isRaisedTeaChosed() {
		return sCInterface.isRaisedTeaChosed();
	}
	
	public synchronized boolean isRaisedExpressoChosed() {
		return sCInterface.isRaisedExpressoChosed();
	}
	
	public synchronized boolean isRaisedCoin10Inserted() {
		return sCInterface.isRaisedCoin10Inserted();
	}
	
	public synchronized boolean isRaisedCoin25Inserted() {
		return sCInterface.isRaisedCoin25Inserted();
	}
	
	public synchronized boolean isRaisedCoin50Inserted() {
		return sCInterface.isRaisedCoin50Inserted();
	}
	
=======
>>>>>>> 68d868c1c4efdf8a22dfb9d5b0c54d4297ed849b
	public synchronized boolean isRaisedCancel() {
		return sCInterface.isRaisedCancel();
	}
	
<<<<<<< HEAD
	public synchronized boolean isRaisedNFCPayment() {
		return sCInterface.isRaisedNFCPayment();
=======
	public synchronized boolean isRaisedNotHotEnough() {
		return sCInterface.isRaisedNotHotEnough();
	}
	
	public synchronized boolean isRaisedHotEnoughOut() {
		return sCInterface.isRaisedHotEnoughOut();
>>>>>>> 68d868c1c4efdf8a22dfb9d5b0c54d4297ed849b
	}
	
	public synchronized boolean isRaisedGiveBackMoney() {
		return sCInterface.isRaisedGiveBackMoney();
	}
	
	public synchronized boolean isRaisedDoTransaction() {
		return sCInterface.isRaisedDoTransaction();
	}
	
	public synchronized boolean getSelected() {
		return sCInterface.getSelected();
	}
	
	public synchronized void setSelected(boolean value) {
		sCInterface.setSelected(value);
	}
	
	public synchronized boolean getPayedEnough() {
		return sCInterface.getPayedEnough();
	}
	
	public synchronized void setPayedEnough(boolean value) {
		sCInterface.setPayedEnough(value);
	}
	
	public synchronized boolean getHotEnough() {
		return sCInterface.getHotEnough();
	}
	
	public synchronized void setHotEnough(boolean value) {
		sCInterface.setHotEnough(value);
	}
	
	public synchronized boolean getGobeletOk() {
		return sCInterface.getGobeletOk();
	}
	
	public synchronized void setGobeletOk(boolean value) {
		sCInterface.setGobeletOk(value);
	}
	
	public synchronized boolean getGobeletTaken() {
		return sCInterface.getGobeletTaken();
	}
	
	public synchronized void setGobeletTaken(boolean value) {
		sCInterface.setGobeletTaken(value);
	}
	
	private void effect_main_region_Step2_tr0() {
		exitSequence_main_region_Step2();
		enterSequence_main_region_Step3_default();
		react();
	}
	
	/* Entry action for state 'Choice and Payment'. */
	private void entryAction_main_region_Choice_and_Payment() {
		timer.setTimer(this, 0, 200, true);
	}
	
	/* Entry action for state 'Chosed or not'. */
	private void entryAction_main_region_Choice_and_Payment_Choice_region_Chosed_or_not() {
		timer.setTimer(this, 1, 5000, false);
	}
	
	/* Entry action for state 'Drink chosed'. */
	private void entryAction_main_region_Choice_and_Payment_Choice_region_Chosed_or_not_r1_Drink_chosed() {
		sCInterface.setSelected(true);
	}
	
	/* Entry action for state 'No choice'. */
	private void entryAction_main_region_Choice_and_Payment_Choice_region_Chosed_or_not_r1_No_choice() {
		sCInterface.setSelected(false);
	}
	
	/* Entry action for state 'Payed or not'. */
	private void entryAction_main_region_Choice_and_Payment_Payment_region_Payed_or_not() {
		timer.setTimer(this, 2, 5000, false);
	}
	
	/* Entry action for state 'No money'. */
	private void entryAction_main_region_Choice_and_Payment_Payment_region_Payed_or_not_r1_No_money() {
		sCInterface.setPayedEnough(false);
	}
	
	/* Entry action for state 'Enough money'. */
	private void entryAction_main_region_Choice_and_Payment_Payment_region_Payed_or_not_r1_Enough_money() {
		sCInterface.setPayedEnough(true);
	}
	
<<<<<<< HEAD
	/* Entry action for state 'Water heat'. */
	private void entryAction_main_region_Step1_r1_Water_heat() {
		sCInterface.raiseWaterHeated();
	}
	
	/* Entry action for state 'First step'. */
	private void entryAction_main_region_Step1_r2_First_step() {
		timer.setTimer(this, 3, 5000, false);
	}
	
	/* Entry action for state 'Cup Placement'. */
	private void entryAction_main_region_Step2_r1_Cup_Placement() {
		timer.setTimer(this, 4, 3000, false);
		
		sCInterface.raiseCupPlacement();
	}
	
	/* Entry action for state 'Second step'. */
	private void entryAction_main_region_Step2_r2_Second_step() {
		timer.setTimer(this, 5, 5000, false);
	}
	
	/* Entry action for state 'Water wait'. */
	private void entryAction_main_region_Step3_r1_Water_wait() {
		sCInterface.raiseWaitForWater();
	}
	
	/* Entry action for state 'Sugar added'. */
	private void entryAction_main_region_Step3_r2_Sugar_added() {
		sCInterface.raiseAddSugar();
=======
	/* Entry action for state 'Gobelet pret'. */
	private void entryAction_main_region_Fin_de_la_commande_R_cup_rer_gobelet_Gobelet_pret() {
		sCInterface.raiseGobeletIsReady();
	}
	
	/* Entry action for state 'Gobelet récupéré'. */
	private void entryAction_main_region_Fin_de_la_commande_R_cup_rer_gobelet_Gobelet_r_cup_r_() {
		sCInterface.raiseGobeletIsTaken();
	}
	
	/* Entry action for state 'Preparation de la boisson'. */
	private void entryAction_main_region_Preparation_de_la_boisson() {
		timer.setTimer(this, 3, 50000, false);
	}
	
	/* Entry action for state 'Chauffage'. */
	private void entryAction_main_region_Preparation_de_la_boisson_eau_Chauffage() {
		timer.setTimer(this, 4, 200, true);
		
		sCInterface.raiseNotHotEnough();
	}
	
	/* Entry action for state 'AssezChauffé'. */
	private void entryAction_main_region_Preparation_de_la_boisson_eau_AssezChauff_() {
		timer.setTimer(this, 5, 200, true);
		
		sCInterface.raiseHotEnoughOut();
>>>>>>> 68d868c1c4efdf8a22dfb9d5b0c54d4297ed849b
	}
	
	/* Exit action for state 'Choice and Payment'. */
	private void exitAction_main_region_Choice_and_Payment() {
		timer.unsetTimer(this, 0);
	}
	
	/* Exit action for state 'Chosed or not'. */
	private void exitAction_main_region_Choice_and_Payment_Choice_region_Chosed_or_not() {
		timer.unsetTimer(this, 1);
	}
	
	/* Exit action for state 'Payed or not'. */
	private void exitAction_main_region_Choice_and_Payment_Payment_region_Payed_or_not() {
		timer.unsetTimer(this, 2);
	}
	
<<<<<<< HEAD
	/* Exit action for state 'First step'. */
	private void exitAction_main_region_Step1_r2_First_step() {
		timer.unsetTimer(this, 3);
	}
	
	/* Exit action for state 'Cup Placement'. */
	private void exitAction_main_region_Step2_r1_Cup_Placement() {
		timer.unsetTimer(this, 4);
	}
	
	/* Exit action for state 'Second step'. */
	private void exitAction_main_region_Step2_r2_Second_step() {
=======
	/* Exit action for state 'Preparation de la boisson'. */
	private void exitAction_main_region_Preparation_de_la_boisson() {
		timer.unsetTimer(this, 3);
	}
	
	/* Exit action for state 'Chauffage'. */
	private void exitAction_main_region_Preparation_de_la_boisson_eau_Chauffage() {
		timer.unsetTimer(this, 4);
	}
	
	/* Exit action for state 'AssezChauffé'. */
	private void exitAction_main_region_Preparation_de_la_boisson_eau_AssezChauff_() {
>>>>>>> 68d868c1c4efdf8a22dfb9d5b0c54d4297ed849b
		timer.unsetTimer(this, 5);
	}
	
	/* 'default' enter sequence for state Choice and Payment */
	private void enterSequence_main_region_Choice_and_Payment_default() {
		entryAction_main_region_Choice_and_Payment();
		enterSequence_main_region_Choice_and_Payment_Choice_region_default();
		enterSequence_main_region_Choice_and_Payment_Payment_region_default();
	}
	
	/* 'default' enter sequence for state Chosed or not */
	private void enterSequence_main_region_Choice_and_Payment_Choice_region_Chosed_or_not_default() {
		entryAction_main_region_Choice_and_Payment_Choice_region_Chosed_or_not();
		enterSequence_main_region_Choice_and_Payment_Choice_region_Chosed_or_not_r1_default();
	}
	
	/* 'default' enter sequence for state Drink chosed */
	private void enterSequence_main_region_Choice_and_Payment_Choice_region_Chosed_or_not_r1_Drink_chosed_default() {
		entryAction_main_region_Choice_and_Payment_Choice_region_Chosed_or_not_r1_Drink_chosed();
		nextStateIndex = 0;
		stateVector[0] = State.main_region_Choice_and_Payment_Choice_region_Chosed_or_not_r1_Drink_chosed;
		
		historyVector[0] = stateVector[0];
	}
	
	/* 'default' enter sequence for state No choice */
	private void enterSequence_main_region_Choice_and_Payment_Choice_region_Chosed_or_not_r1_No_choice_default() {
		entryAction_main_region_Choice_and_Payment_Choice_region_Chosed_or_not_r1_No_choice();
		nextStateIndex = 0;
		stateVector[0] = State.main_region_Choice_and_Payment_Choice_region_Chosed_or_not_r1_No_choice;
		
		historyVector[0] = stateVector[0];
	}
	
	/* 'default' enter sequence for state Payed or not */
	private void enterSequence_main_region_Choice_and_Payment_Payment_region_Payed_or_not_default() {
		entryAction_main_region_Choice_and_Payment_Payment_region_Payed_or_not();
		enterSequence_main_region_Choice_and_Payment_Payment_region_Payed_or_not_r1_default();
	}
	
	/* 'default' enter sequence for state No money */
	private void enterSequence_main_region_Choice_and_Payment_Payment_region_Payed_or_not_r1_No_money_default() {
		entryAction_main_region_Choice_and_Payment_Payment_region_Payed_or_not_r1_No_money();
		nextStateIndex = 1;
		stateVector[1] = State.main_region_Choice_and_Payment_Payment_region_Payed_or_not_r1_No_money;
		
		historyVector[1] = stateVector[1];
	}
	
	/* 'default' enter sequence for state Money inserted */
	private void enterSequence_main_region_Choice_and_Payment_Payment_region_Payed_or_not_r1_Money_inserted_default() {
		nextStateIndex = 1;
		stateVector[1] = State.main_region_Choice_and_Payment_Payment_region_Payed_or_not_r1_Money_inserted;
		
		historyVector[1] = stateVector[1];
	}
	
	/* 'default' enter sequence for state Enough money */
	private void enterSequence_main_region_Choice_and_Payment_Payment_region_Payed_or_not_r1_Enough_money_default() {
		entryAction_main_region_Choice_and_Payment_Payment_region_Payed_or_not_r1_Enough_money();
		nextStateIndex = 1;
		stateVector[1] = State.main_region_Choice_and_Payment_Payment_region_Payed_or_not_r1_Enough_money;
		
		historyVector[1] = stateVector[1];
	}
	
<<<<<<< HEAD
	/* 'default' enter sequence for state Step1 */
	private void enterSequence_main_region_Step1_default() {
		enterSequence_main_region_Step1_r1_default();
		enterSequence_main_region_Step1_r2_default();
	}
	
	/* 'default' enter sequence for state Water heat */
	private void enterSequence_main_region_Step1_r1_Water_heat_default() {
		entryAction_main_region_Step1_r1_Water_heat();
		nextStateIndex = 0;
		stateVector[0] = State.main_region_Step1_r1_Water_heat;
	}
	
	/* Default enter sequence for state null */
	private void enterSequence_main_region_Step1_r1__final__default() {
		nextStateIndex = 0;
		stateVector[0] = State.main_region_Step1_r1__final_;
	}
	
	/* 'default' enter sequence for state First step */
	private void enterSequence_main_region_Step1_r2_First_step_default() {
		entryAction_main_region_Step1_r2_First_step();
		nextStateIndex = 1;
		stateVector[1] = State.main_region_Step1_r2_First_step;
	}
	
	/* 'default' enter sequence for state Drink difference */
	private void enterSequence_main_region_Step1_r2_Drink_difference_default() {
		nextStateIndex = 1;
		stateVector[1] = State.main_region_Step1_r2_Drink_difference;
	}
	
	/* Default enter sequence for state null */
	private void enterSequence_main_region_Step1_r2__final__default() {
		nextStateIndex = 1;
		stateVector[1] = State.main_region_Step1_r2__final_;
	}
	
	/* 'default' enter sequence for state Step2 */
	private void enterSequence_main_region_Step2_default() {
		enterSequence_main_region_Step2_r1_default();
		enterSequence_main_region_Step2_r2_default();
	}
	
	/* 'default' enter sequence for state Cup Placement */
	private void enterSequence_main_region_Step2_r1_Cup_Placement_default() {
		entryAction_main_region_Step2_r1_Cup_Placement();
		nextStateIndex = 0;
		stateVector[0] = State.main_region_Step2_r1_Cup_Placement;
	}
	
	/* 'default' enter sequence for state Drink difference */
	private void enterSequence_main_region_Step2_r2_Drink_difference_default() {
		nextStateIndex = 1;
		stateVector[1] = State.main_region_Step2_r2_Drink_difference;
	}
	
	/* 'default' enter sequence for state Second step */
	private void enterSequence_main_region_Step2_r2_Second_step_default() {
		entryAction_main_region_Step2_r2_Second_step();
		nextStateIndex = 1;
		stateVector[1] = State.main_region_Step2_r2_Second_step;
	}
	
	/* 'default' enter sequence for state Step3 */
	private void enterSequence_main_region_Step3_default() {
		enterSequence_main_region_Step3_r1_default();
		enterSequence_main_region_Step3_r2_default();
	}
	
	/* 'default' enter sequence for state Water wait */
	private void enterSequence_main_region_Step3_r1_Water_wait_default() {
		entryAction_main_region_Step3_r1_Water_wait();
=======
	/* 'default' enter sequence for state Fin de la commande */
	private void enterSequence_main_region_Fin_de_la_commande_default() {
		enterSequence_main_region_Fin_de_la_commande_nettoyage_default();
		enterSequence_main_region_Fin_de_la_commande_fin_de_la_commande_rendu_monnaie_default();
		enterSequence_main_region_Fin_de_la_commande_R_cup_rer_gobelet_default();
	}
	
	/* 'default' enter sequence for state Nettoyage */
	private void enterSequence_main_region_Fin_de_la_commande_nettoyage_Nettoyage_default() {
		nextStateIndex = 0;
		stateVector[0] = State.main_region_Fin_de_la_commande_nettoyage_Nettoyage;
	}
	
	/* 'default' enter sequence for state Rendre monnaie */
	private void enterSequence_main_region_Fin_de_la_commande_fin_de_la_commande_rendu_monnaie_Rendre_monnaie_default() {
		nextStateIndex = 1;
		stateVector[1] = State.main_region_Fin_de_la_commande_fin_de_la_commande_rendu_monnaie_Rendre_monnaie;
	}
	
	/* 'default' enter sequence for state Gobelet pret */
	private void enterSequence_main_region_Fin_de_la_commande_R_cup_rer_gobelet_Gobelet_pret_default() {
		entryAction_main_region_Fin_de_la_commande_R_cup_rer_gobelet_Gobelet_pret();
		nextStateIndex = 2;
		stateVector[2] = State.main_region_Fin_de_la_commande_R_cup_rer_gobelet_Gobelet_pret;
	}
	
	/* 'default' enter sequence for state Gobelet récupéré */
	private void enterSequence_main_region_Fin_de_la_commande_R_cup_rer_gobelet_Gobelet_r_cup_r__default() {
		entryAction_main_region_Fin_de_la_commande_R_cup_rer_gobelet_Gobelet_r_cup_r_();
		nextStateIndex = 2;
		stateVector[2] = State.main_region_Fin_de_la_commande_R_cup_rer_gobelet_Gobelet_r_cup_r_;
	}
	
	/* 'default' enter sequence for state Preparation de la boisson */
	private void enterSequence_main_region_Preparation_de_la_boisson_default() {
		entryAction_main_region_Preparation_de_la_boisson();
		enterSequence_main_region_Preparation_de_la_boisson_gobelet_default();
		enterSequence_main_region_Preparation_de_la_boisson_eau_default();
	}
	
	/* 'default' enter sequence for state Positionnement dosette */
	private void enterSequence_main_region_Preparation_de_la_boisson_gobelet_Positionnement_dosette_default() {
		nextStateIndex = 0;
		stateVector[0] = State.main_region_Preparation_de_la_boisson_gobelet_Positionnement_dosette;
	}
	
	/* 'default' enter sequence for state Positionnement gobelet */
	private void enterSequence_main_region_Preparation_de_la_boisson_gobelet_Positionnement_gobelet_default() {
		nextStateIndex = 0;
		stateVector[0] = State.main_region_Preparation_de_la_boisson_gobelet_Positionnement_gobelet;
	}
	
	/* 'default' enter sequence for state Ajout du sucre */
	private void enterSequence_main_region_Preparation_de_la_boisson_gobelet_Ajout_du_sucre_default() {
		nextStateIndex = 0;
		stateVector[0] = State.main_region_Preparation_de_la_boisson_gobelet_Ajout_du_sucre;
	}
	
	/* 'default' enter sequence for state Chauffage */
	private void enterSequence_main_region_Preparation_de_la_boisson_eau_Chauffage_default() {
		entryAction_main_region_Preparation_de_la_boisson_eau_Chauffage();
		nextStateIndex = 1;
		stateVector[1] = State.main_region_Preparation_de_la_boisson_eau_Chauffage;
	}
	
	/* 'default' enter sequence for state AssezChauffé */
	private void enterSequence_main_region_Preparation_de_la_boisson_eau_AssezChauff__default() {
		entryAction_main_region_Preparation_de_la_boisson_eau_AssezChauff_();
		nextStateIndex = 1;
		stateVector[1] = State.main_region_Preparation_de_la_boisson_eau_AssezChauff_;
	}
	
	/* 'default' enter sequence for state Versement de l'eau */
	private void enterSequence_main_region_Preparation_de_la_boisson_eau_Versement_de_l_eau_default() {
		nextStateIndex = 1;
		stateVector[1] = State.main_region_Preparation_de_la_boisson_eau_Versement_de_l_eau;
	}
	
	/* 'default' enter sequence for state End */
	private void enterSequence_main_region_End_default() {
>>>>>>> 68d868c1c4efdf8a22dfb9d5b0c54d4297ed849b
		nextStateIndex = 0;
		stateVector[0] = State.main_region_Step3_r1_Water_wait;
	}
	
	/* 'default' enter sequence for state Sugar added */
	private void enterSequence_main_region_Step3_r2_Sugar_added_default() {
		entryAction_main_region_Step3_r2_Sugar_added();
		nextStateIndex = 1;
		stateVector[1] = State.main_region_Step3_r2_Sugar_added;
	}
	
	/* 'default' enter sequence for region main region */
	private void enterSequence_main_region_default() {
		react_main_region__entry_Default();
	}
	
	/* 'default' enter sequence for region Choice region */
	private void enterSequence_main_region_Choice_and_Payment_Choice_region_default() {
		react_main_region_Choice_and_Payment_Choice_region__entry_Default();
	}
	
	/* 'default' enter sequence for region r1 */
	private void enterSequence_main_region_Choice_and_Payment_Choice_region_Chosed_or_not_r1_default() {
		react_main_region_Choice_and_Payment_Choice_region_Chosed_or_not_r1__entry_Default();
	}
	
	/* shallow enterSequence with history in child r1 */
	private void shallowEnterSequence_main_region_Choice_and_Payment_Choice_region_Chosed_or_not_r1() {
		switch (historyVector[0]) {
		case main_region_Choice_and_Payment_Choice_region_Chosed_or_not_r1_Drink_chosed:
			enterSequence_main_region_Choice_and_Payment_Choice_region_Chosed_or_not_r1_Drink_chosed_default();
			break;
		case main_region_Choice_and_Payment_Choice_region_Chosed_or_not_r1_No_choice:
			enterSequence_main_region_Choice_and_Payment_Choice_region_Chosed_or_not_r1_No_choice_default();
			break;
		default:
			break;
		}
	}
	
	/* 'default' enter sequence for region Payment region */
	private void enterSequence_main_region_Choice_and_Payment_Payment_region_default() {
		react_main_region_Choice_and_Payment_Payment_region__entry_Default();
	}
	
	/* 'default' enter sequence for region r1 */
	private void enterSequence_main_region_Choice_and_Payment_Payment_region_Payed_or_not_r1_default() {
		react_main_region_Choice_and_Payment_Payment_region_Payed_or_not_r1__entry_Default();
	}
	
	/* shallow enterSequence with history in child r1 */
	private void shallowEnterSequence_main_region_Choice_and_Payment_Payment_region_Payed_or_not_r1() {
		switch (historyVector[1]) {
		case main_region_Choice_and_Payment_Payment_region_Payed_or_not_r1_No_money:
			enterSequence_main_region_Choice_and_Payment_Payment_region_Payed_or_not_r1_No_money_default();
			break;
		case main_region_Choice_and_Payment_Payment_region_Payed_or_not_r1_Money_inserted:
			enterSequence_main_region_Choice_and_Payment_Payment_region_Payed_or_not_r1_Money_inserted_default();
			break;
		case main_region_Choice_and_Payment_Payment_region_Payed_or_not_r1_Enough_money:
			enterSequence_main_region_Choice_and_Payment_Payment_region_Payed_or_not_r1_Enough_money_default();
			break;
		default:
			break;
		}
	}
	
<<<<<<< HEAD
	/* 'default' enter sequence for region r1 */
	private void enterSequence_main_region_Step1_r1_default() {
		react_main_region_Step1_r1__entry_Default();
=======
	/* 'default' enter sequence for region nettoyage */
	private void enterSequence_main_region_Fin_de_la_commande_nettoyage_default() {
		react_main_region_Fin_de_la_commande_nettoyage__entry_Default();
	}
	
	/* 'default' enter sequence for region fin de la commande/rendu monnaie */
	private void enterSequence_main_region_Fin_de_la_commande_fin_de_la_commande_rendu_monnaie_default() {
		react_main_region_Fin_de_la_commande_fin_de_la_commande_rendu_monnaie__entry_Default();
	}
	
	/* 'default' enter sequence for region Récupérer gobelet */
	private void enterSequence_main_region_Fin_de_la_commande_R_cup_rer_gobelet_default() {
		react_main_region_Fin_de_la_commande_R_cup_rer_gobelet__entry_Default();
	}
	
	/* 'default' enter sequence for region gobelet */
	private void enterSequence_main_region_Preparation_de_la_boisson_gobelet_default() {
		react_main_region_Preparation_de_la_boisson_gobelet__entry_Default();
	}
	
	/* 'default' enter sequence for region eau */
	private void enterSequence_main_region_Preparation_de_la_boisson_eau_default() {
		react_main_region_Preparation_de_la_boisson_eau__entry_Default();
	}
	
	/* Default exit sequence for state Choice and Payment */
	private void exitSequence_main_region_Choice_and_Payment() {
		exitSequence_main_region_Choice_and_Payment_Choice_region();
		exitSequence_main_region_Choice_and_Payment_Payment_region();
		exitAction_main_region_Choice_and_Payment();
>>>>>>> 68d868c1c4efdf8a22dfb9d5b0c54d4297ed849b
	}
	
	/* 'default' enter sequence for region r2 */
	private void enterSequence_main_region_Step1_r2_default() {
		react_main_region_Step1_r2__entry_Default();
	}
	
	/* 'default' enter sequence for region r1 */
	private void enterSequence_main_region_Step2_r1_default() {
		react_main_region_Step2_r1__entry_Default();
	}
	
	/* 'default' enter sequence for region r2 */
	private void enterSequence_main_region_Step2_r2_default() {
		react_main_region_Step2_r2__entry_Default();
	}
	
	/* 'default' enter sequence for region r1 */
	private void enterSequence_main_region_Step3_r1_default() {
		react_main_region_Step3_r1__entry_Default();
	}
	
	/* 'default' enter sequence for region r2 */
	private void enterSequence_main_region_Step3_r2_default() {
		react_main_region_Step3_r2__entry_Default();
	}
	
	/* Default exit sequence for state Choice and Payment */
	private void exitSequence_main_region_Choice_and_Payment() {
		exitSequence_main_region_Choice_and_Payment_Choice_region();
		exitSequence_main_region_Choice_and_Payment_Payment_region();
		exitAction_main_region_Choice_and_Payment();
	}
	
	/* Default exit sequence for state Chosed or not */
	private void exitSequence_main_region_Choice_and_Payment_Choice_region_Chosed_or_not() {
		exitSequence_main_region_Choice_and_Payment_Choice_region_Chosed_or_not_r1();
		exitAction_main_region_Choice_and_Payment_Choice_region_Chosed_or_not();
	}
	
	/* Default exit sequence for state Drink chosed */
	private void exitSequence_main_region_Choice_and_Payment_Choice_region_Chosed_or_not_r1_Drink_chosed() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
	}
	
	/* Default exit sequence for state No choice */
	private void exitSequence_main_region_Choice_and_Payment_Choice_region_Chosed_or_not_r1_No_choice() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
	}
	
	/* Default exit sequence for state Payed or not */
	private void exitSequence_main_region_Choice_and_Payment_Payment_region_Payed_or_not() {
		exitSequence_main_region_Choice_and_Payment_Payment_region_Payed_or_not_r1();
		exitAction_main_region_Choice_and_Payment_Payment_region_Payed_or_not();
	}
	
	/* Default exit sequence for state No money */
	private void exitSequence_main_region_Choice_and_Payment_Payment_region_Payed_or_not_r1_No_money() {
		nextStateIndex = 1;
		stateVector[1] = State.$NullState$;
	}
	
	/* Default exit sequence for state Money inserted */
	private void exitSequence_main_region_Choice_and_Payment_Payment_region_Payed_or_not_r1_Money_inserted() {
		nextStateIndex = 1;
		stateVector[1] = State.$NullState$;
	}
	
	/* Default exit sequence for state Enough money */
	private void exitSequence_main_region_Choice_and_Payment_Payment_region_Payed_or_not_r1_Enough_money() {
		nextStateIndex = 1;
		stateVector[1] = State.$NullState$;
	}
	
<<<<<<< HEAD
	/* Default exit sequence for state Step1 */
	private void exitSequence_main_region_Step1() {
		exitSequence_main_region_Step1_r1();
		exitSequence_main_region_Step1_r2();
	}
	
	/* Default exit sequence for state Water heat */
	private void exitSequence_main_region_Step1_r1_Water_heat() {
=======
	/* Default exit sequence for state Fin de la commande */
	private void exitSequence_main_region_Fin_de_la_commande() {
		exitSequence_main_region_Fin_de_la_commande_nettoyage();
		exitSequence_main_region_Fin_de_la_commande_fin_de_la_commande_rendu_monnaie();
		exitSequence_main_region_Fin_de_la_commande_R_cup_rer_gobelet();
	}
	
	/* Default exit sequence for state Nettoyage */
	private void exitSequence_main_region_Fin_de_la_commande_nettoyage_Nettoyage() {
>>>>>>> 68d868c1c4efdf8a22dfb9d5b0c54d4297ed849b
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
	}
	
<<<<<<< HEAD
	/* Default exit sequence for final state. */
	private void exitSequence_main_region_Step1_r1__final_() {
=======
	/* Default exit sequence for state Rendre monnaie */
	private void exitSequence_main_region_Fin_de_la_commande_fin_de_la_commande_rendu_monnaie_Rendre_monnaie() {
		nextStateIndex = 1;
		stateVector[1] = State.$NullState$;
	}
	
	/* Default exit sequence for state Gobelet pret */
	private void exitSequence_main_region_Fin_de_la_commande_R_cup_rer_gobelet_Gobelet_pret() {
		nextStateIndex = 2;
		stateVector[2] = State.$NullState$;
	}
	
	/* Default exit sequence for state Gobelet récupéré */
	private void exitSequence_main_region_Fin_de_la_commande_R_cup_rer_gobelet_Gobelet_r_cup_r_() {
		nextStateIndex = 2;
		stateVector[2] = State.$NullState$;
	}
	
	/* Default exit sequence for state Preparation de la boisson */
	private void exitSequence_main_region_Preparation_de_la_boisson() {
		exitSequence_main_region_Preparation_de_la_boisson_gobelet();
		exitSequence_main_region_Preparation_de_la_boisson_eau();
		exitAction_main_region_Preparation_de_la_boisson();
	}
	
	/* Default exit sequence for state Positionnement dosette */
	private void exitSequence_main_region_Preparation_de_la_boisson_gobelet_Positionnement_dosette() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
	}
	
	/* Default exit sequence for state Positionnement gobelet */
	private void exitSequence_main_region_Preparation_de_la_boisson_gobelet_Positionnement_gobelet() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
	}
	
	/* Default exit sequence for state Ajout du sucre */
	private void exitSequence_main_region_Preparation_de_la_boisson_gobelet_Ajout_du_sucre() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
	}
	
	/* Default exit sequence for state Chauffage */
	private void exitSequence_main_region_Preparation_de_la_boisson_eau_Chauffage() {
		nextStateIndex = 1;
		stateVector[1] = State.$NullState$;
		
		exitAction_main_region_Preparation_de_la_boisson_eau_Chauffage();
	}
	
	/* Default exit sequence for state AssezChauffé */
	private void exitSequence_main_region_Preparation_de_la_boisson_eau_AssezChauff_() {
		nextStateIndex = 1;
		stateVector[1] = State.$NullState$;
		
		exitAction_main_region_Preparation_de_la_boisson_eau_AssezChauff_();
	}
	
	/* Default exit sequence for state Versement de l'eau */
	private void exitSequence_main_region_Preparation_de_la_boisson_eau_Versement_de_l_eau() {
		nextStateIndex = 1;
		stateVector[1] = State.$NullState$;
	}
	
	/* Default exit sequence for state End */
	private void exitSequence_main_region_End() {
>>>>>>> 68d868c1c4efdf8a22dfb9d5b0c54d4297ed849b
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
	}
	
	/* Default exit sequence for state First step */
	private void exitSequence_main_region_Step1_r2_First_step() {
		nextStateIndex = 1;
		stateVector[1] = State.$NullState$;
		
		exitAction_main_region_Step1_r2_First_step();
	}
	
	/* Default exit sequence for state Drink difference */
	private void exitSequence_main_region_Step1_r2_Drink_difference() {
		nextStateIndex = 1;
		stateVector[1] = State.$NullState$;
	}
	
	/* Default exit sequence for final state. */
	private void exitSequence_main_region_Step1_r2__final_() {
		nextStateIndex = 1;
		stateVector[1] = State.$NullState$;
	}
	
	/* Default exit sequence for state Step2 */
	private void exitSequence_main_region_Step2() {
		exitSequence_main_region_Step2_r1();
		exitSequence_main_region_Step2_r2();
	}
	
	/* Default exit sequence for state Cup Placement */
	private void exitSequence_main_region_Step2_r1_Cup_Placement() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
		
		exitAction_main_region_Step2_r1_Cup_Placement();
	}
	
	/* Default exit sequence for state Drink difference */
	private void exitSequence_main_region_Step2_r2_Drink_difference() {
		nextStateIndex = 1;
		stateVector[1] = State.$NullState$;
	}
	
	/* Default exit sequence for state Second step */
	private void exitSequence_main_region_Step2_r2_Second_step() {
		nextStateIndex = 1;
		stateVector[1] = State.$NullState$;
		
		exitAction_main_region_Step2_r2_Second_step();
	}
	
	/* Default exit sequence for state Water wait */
	private void exitSequence_main_region_Step3_r1_Water_wait() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
	}
	
	/* Default exit sequence for state Sugar added */
	private void exitSequence_main_region_Step3_r2_Sugar_added() {
		nextStateIndex = 1;
		stateVector[1] = State.$NullState$;
	}
	
	/* Default exit sequence for region main region */
	private void exitSequence_main_region() {
		switch (stateVector[0]) {
		case main_region_Choice_and_Payment_Choice_region_Chosed_or_not_r1_Drink_chosed:
			exitSequence_main_region_Choice_and_Payment_Choice_region_Chosed_or_not_r1_Drink_chosed();
			exitAction_main_region_Choice_and_Payment_Choice_region_Chosed_or_not();
			break;
		case main_region_Choice_and_Payment_Choice_region_Chosed_or_not_r1_No_choice:
			exitSequence_main_region_Choice_and_Payment_Choice_region_Chosed_or_not_r1_No_choice();
			exitAction_main_region_Choice_and_Payment_Choice_region_Chosed_or_not();
			break;
<<<<<<< HEAD
		case main_region_Step1_r1_Water_heat:
			exitSequence_main_region_Step1_r1_Water_heat();
			break;
		case main_region_Step1_r1__final_:
			exitSequence_main_region_Step1_r1__final_();
			break;
		case main_region_Step2_r1_Cup_Placement:
			exitSequence_main_region_Step2_r1_Cup_Placement();
			break;
		case main_region_Step3_r1_Water_wait:
			exitSequence_main_region_Step3_r1_Water_wait();
=======
		case main_region_Fin_de_la_commande_nettoyage_Nettoyage:
			exitSequence_main_region_Fin_de_la_commande_nettoyage_Nettoyage();
			break;
		case main_region_Preparation_de_la_boisson_gobelet_Positionnement_dosette:
			exitSequence_main_region_Preparation_de_la_boisson_gobelet_Positionnement_dosette();
			break;
		case main_region_Preparation_de_la_boisson_gobelet_Positionnement_gobelet:
			exitSequence_main_region_Preparation_de_la_boisson_gobelet_Positionnement_gobelet();
			break;
		case main_region_Preparation_de_la_boisson_gobelet_Ajout_du_sucre:
			exitSequence_main_region_Preparation_de_la_boisson_gobelet_Ajout_du_sucre();
			break;
		case main_region_End:
			exitSequence_main_region_End();
>>>>>>> 68d868c1c4efdf8a22dfb9d5b0c54d4297ed849b
			break;
		default:
			break;
		}
		
		switch (stateVector[1]) {
		case main_region_Choice_and_Payment_Payment_region_Payed_or_not_r1_No_money:
			exitSequence_main_region_Choice_and_Payment_Payment_region_Payed_or_not_r1_No_money();
			exitAction_main_region_Choice_and_Payment_Payment_region_Payed_or_not();
			exitAction_main_region_Choice_and_Payment();
			break;
		case main_region_Choice_and_Payment_Payment_region_Payed_or_not_r1_Money_inserted:
			exitSequence_main_region_Choice_and_Payment_Payment_region_Payed_or_not_r1_Money_inserted();
			exitAction_main_region_Choice_and_Payment_Payment_region_Payed_or_not();
			exitAction_main_region_Choice_and_Payment();
			break;
		case main_region_Choice_and_Payment_Payment_region_Payed_or_not_r1_Enough_money:
			exitSequence_main_region_Choice_and_Payment_Payment_region_Payed_or_not_r1_Enough_money();
			exitAction_main_region_Choice_and_Payment_Payment_region_Payed_or_not();
			exitAction_main_region_Choice_and_Payment();
			break;
<<<<<<< HEAD
		case main_region_Step1_r2_First_step:
			exitSequence_main_region_Step1_r2_First_step();
			break;
		case main_region_Step1_r2_Drink_difference:
			exitSequence_main_region_Step1_r2_Drink_difference();
			break;
		case main_region_Step1_r2__final_:
			exitSequence_main_region_Step1_r2__final_();
			break;
		case main_region_Step2_r2_Drink_difference:
			exitSequence_main_region_Step2_r2_Drink_difference();
			break;
		case main_region_Step2_r2_Second_step:
			exitSequence_main_region_Step2_r2_Second_step();
			break;
		case main_region_Step3_r2_Sugar_added:
			exitSequence_main_region_Step3_r2_Sugar_added();
=======
		case main_region_Fin_de_la_commande_fin_de_la_commande_rendu_monnaie_Rendre_monnaie:
			exitSequence_main_region_Fin_de_la_commande_fin_de_la_commande_rendu_monnaie_Rendre_monnaie();
			break;
		case main_region_Preparation_de_la_boisson_eau_Chauffage:
			exitSequence_main_region_Preparation_de_la_boisson_eau_Chauffage();
			exitAction_main_region_Preparation_de_la_boisson();
			break;
		case main_region_Preparation_de_la_boisson_eau_AssezChauff_:
			exitSequence_main_region_Preparation_de_la_boisson_eau_AssezChauff_();
			exitAction_main_region_Preparation_de_la_boisson();
			break;
		case main_region_Preparation_de_la_boisson_eau_Versement_de_l_eau:
			exitSequence_main_region_Preparation_de_la_boisson_eau_Versement_de_l_eau();
			exitAction_main_region_Preparation_de_la_boisson();
			break;
		default:
			break;
		}
		
		switch (stateVector[2]) {
		case main_region_Fin_de_la_commande_R_cup_rer_gobelet_Gobelet_pret:
			exitSequence_main_region_Fin_de_la_commande_R_cup_rer_gobelet_Gobelet_pret();
			break;
		case main_region_Fin_de_la_commande_R_cup_rer_gobelet_Gobelet_r_cup_r_:
			exitSequence_main_region_Fin_de_la_commande_R_cup_rer_gobelet_Gobelet_r_cup_r_();
>>>>>>> 68d868c1c4efdf8a22dfb9d5b0c54d4297ed849b
			break;
		default:
			break;
		}
	}
	
	/* Default exit sequence for region Choice region */
	private void exitSequence_main_region_Choice_and_Payment_Choice_region() {
		switch (stateVector[0]) {
		case main_region_Choice_and_Payment_Choice_region_Chosed_or_not_r1_Drink_chosed:
			exitSequence_main_region_Choice_and_Payment_Choice_region_Chosed_or_not_r1_Drink_chosed();
			exitAction_main_region_Choice_and_Payment_Choice_region_Chosed_or_not();
			break;
		case main_region_Choice_and_Payment_Choice_region_Chosed_or_not_r1_No_choice:
			exitSequence_main_region_Choice_and_Payment_Choice_region_Chosed_or_not_r1_No_choice();
			exitAction_main_region_Choice_and_Payment_Choice_region_Chosed_or_not();
			break;
		default:
			break;
		}
	}
	
	/* Default exit sequence for region r1 */
	private void exitSequence_main_region_Choice_and_Payment_Choice_region_Chosed_or_not_r1() {
		switch (stateVector[0]) {
		case main_region_Choice_and_Payment_Choice_region_Chosed_or_not_r1_Drink_chosed:
			exitSequence_main_region_Choice_and_Payment_Choice_region_Chosed_or_not_r1_Drink_chosed();
			break;
		case main_region_Choice_and_Payment_Choice_region_Chosed_or_not_r1_No_choice:
			exitSequence_main_region_Choice_and_Payment_Choice_region_Chosed_or_not_r1_No_choice();
			break;
		default:
			break;
		}
	}
	
	/* Default exit sequence for region Payment region */
	private void exitSequence_main_region_Choice_and_Payment_Payment_region() {
		switch (stateVector[1]) {
		case main_region_Choice_and_Payment_Payment_region_Payed_or_not_r1_No_money:
			exitSequence_main_region_Choice_and_Payment_Payment_region_Payed_or_not_r1_No_money();
			exitAction_main_region_Choice_and_Payment_Payment_region_Payed_or_not();
			break;
		case main_region_Choice_and_Payment_Payment_region_Payed_or_not_r1_Money_inserted:
			exitSequence_main_region_Choice_and_Payment_Payment_region_Payed_or_not_r1_Money_inserted();
			exitAction_main_region_Choice_and_Payment_Payment_region_Payed_or_not();
			break;
		case main_region_Choice_and_Payment_Payment_region_Payed_or_not_r1_Enough_money:
			exitSequence_main_region_Choice_and_Payment_Payment_region_Payed_or_not_r1_Enough_money();
			exitAction_main_region_Choice_and_Payment_Payment_region_Payed_or_not();
			break;
		default:
			break;
		}
	}
	
	/* Default exit sequence for region r1 */
	private void exitSequence_main_region_Choice_and_Payment_Payment_region_Payed_or_not_r1() {
		switch (stateVector[1]) {
		case main_region_Choice_and_Payment_Payment_region_Payed_or_not_r1_No_money:
			exitSequence_main_region_Choice_and_Payment_Payment_region_Payed_or_not_r1_No_money();
			break;
		case main_region_Choice_and_Payment_Payment_region_Payed_or_not_r1_Money_inserted:
			exitSequence_main_region_Choice_and_Payment_Payment_region_Payed_or_not_r1_Money_inserted();
			break;
		case main_region_Choice_and_Payment_Payment_region_Payed_or_not_r1_Enough_money:
			exitSequence_main_region_Choice_and_Payment_Payment_region_Payed_or_not_r1_Enough_money();
			break;
		default:
			break;
		}
	}
	
<<<<<<< HEAD
	/* Default exit sequence for region r1 */
	private void exitSequence_main_region_Step1_r1() {
		switch (stateVector[0]) {
		case main_region_Step1_r1_Water_heat:
			exitSequence_main_region_Step1_r1_Water_heat();
			break;
		case main_region_Step1_r1__final_:
			exitSequence_main_region_Step1_r1__final_();
=======
	/* Default exit sequence for region nettoyage */
	private void exitSequence_main_region_Fin_de_la_commande_nettoyage() {
		switch (stateVector[0]) {
		case main_region_Fin_de_la_commande_nettoyage_Nettoyage:
			exitSequence_main_region_Fin_de_la_commande_nettoyage_Nettoyage();
>>>>>>> 68d868c1c4efdf8a22dfb9d5b0c54d4297ed849b
			break;
		default:
			break;
		}
	}
	
<<<<<<< HEAD
	/* Default exit sequence for region r2 */
	private void exitSequence_main_region_Step1_r2() {
		switch (stateVector[1]) {
		case main_region_Step1_r2_First_step:
			exitSequence_main_region_Step1_r2_First_step();
			break;
		case main_region_Step1_r2_Drink_difference:
			exitSequence_main_region_Step1_r2_Drink_difference();
			break;
		case main_region_Step1_r2__final_:
			exitSequence_main_region_Step1_r2__final_();
=======
	/* Default exit sequence for region fin de la commande/rendu monnaie */
	private void exitSequence_main_region_Fin_de_la_commande_fin_de_la_commande_rendu_monnaie() {
		switch (stateVector[1]) {
		case main_region_Fin_de_la_commande_fin_de_la_commande_rendu_monnaie_Rendre_monnaie:
			exitSequence_main_region_Fin_de_la_commande_fin_de_la_commande_rendu_monnaie_Rendre_monnaie();
>>>>>>> 68d868c1c4efdf8a22dfb9d5b0c54d4297ed849b
			break;
		default:
			break;
		}
	}
	
<<<<<<< HEAD
	/* Default exit sequence for region r1 */
	private void exitSequence_main_region_Step2_r1() {
		switch (stateVector[0]) {
		case main_region_Step2_r1_Cup_Placement:
			exitSequence_main_region_Step2_r1_Cup_Placement();
			break;
		default:
			break;
		}
	}
	
	/* Default exit sequence for region r2 */
	private void exitSequence_main_region_Step2_r2() {
		switch (stateVector[1]) {
		case main_region_Step2_r2_Drink_difference:
			exitSequence_main_region_Step2_r2_Drink_difference();
			break;
		case main_region_Step2_r2_Second_step:
			exitSequence_main_region_Step2_r2_Second_step();
=======
	/* Default exit sequence for region Récupérer gobelet */
	private void exitSequence_main_region_Fin_de_la_commande_R_cup_rer_gobelet() {
		switch (stateVector[2]) {
		case main_region_Fin_de_la_commande_R_cup_rer_gobelet_Gobelet_pret:
			exitSequence_main_region_Fin_de_la_commande_R_cup_rer_gobelet_Gobelet_pret();
			break;
		case main_region_Fin_de_la_commande_R_cup_rer_gobelet_Gobelet_r_cup_r_:
			exitSequence_main_region_Fin_de_la_commande_R_cup_rer_gobelet_Gobelet_r_cup_r_();
>>>>>>> 68d868c1c4efdf8a22dfb9d5b0c54d4297ed849b
			break;
		default:
			break;
		}
	}
	
<<<<<<< HEAD
	/* Default exit sequence for region r1 */
	private void exitSequence_main_region_Step3_r1() {
		switch (stateVector[0]) {
		case main_region_Step3_r1_Water_wait:
			exitSequence_main_region_Step3_r1_Water_wait();
=======
	/* Default exit sequence for region gobelet */
	private void exitSequence_main_region_Preparation_de_la_boisson_gobelet() {
		switch (stateVector[0]) {
		case main_region_Preparation_de_la_boisson_gobelet_Positionnement_dosette:
			exitSequence_main_region_Preparation_de_la_boisson_gobelet_Positionnement_dosette();
			break;
		case main_region_Preparation_de_la_boisson_gobelet_Positionnement_gobelet:
			exitSequence_main_region_Preparation_de_la_boisson_gobelet_Positionnement_gobelet();
			break;
		case main_region_Preparation_de_la_boisson_gobelet_Ajout_du_sucre:
			exitSequence_main_region_Preparation_de_la_boisson_gobelet_Ajout_du_sucre();
>>>>>>> 68d868c1c4efdf8a22dfb9d5b0c54d4297ed849b
			break;
		default:
			break;
		}
	}
	
<<<<<<< HEAD
	/* Default exit sequence for region r2 */
	private void exitSequence_main_region_Step3_r2() {
		switch (stateVector[1]) {
		case main_region_Step3_r2_Sugar_added:
			exitSequence_main_region_Step3_r2_Sugar_added();
=======
	/* Default exit sequence for region eau */
	private void exitSequence_main_region_Preparation_de_la_boisson_eau() {
		switch (stateVector[1]) {
		case main_region_Preparation_de_la_boisson_eau_Chauffage:
			exitSequence_main_region_Preparation_de_la_boisson_eau_Chauffage();
			break;
		case main_region_Preparation_de_la_boisson_eau_AssezChauff_:
			exitSequence_main_region_Preparation_de_la_boisson_eau_AssezChauff_();
			break;
		case main_region_Preparation_de_la_boisson_eau_Versement_de_l_eau:
			exitSequence_main_region_Preparation_de_la_boisson_eau_Versement_de_l_eau();
>>>>>>> 68d868c1c4efdf8a22dfb9d5b0c54d4297ed849b
			break;
		default:
			break;
		}
	}
	
	/* Default react sequence for initial entry  */
	private void react_main_region__entry_Default() {
		enterSequence_main_region_Choice_and_Payment_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react_main_region_Choice_and_Payment_Choice_region_Chosed_or_not_r1__entry_Default() {
		enterSequence_main_region_Choice_and_Payment_Choice_region_Chosed_or_not_r1_No_choice_default();
	}
	
	/* Default react sequence for shallow history entry history */
	private void react_main_region_Choice_and_Payment_Choice_region_Chosed_or_not_r1_history() {
		/* Enter the region with shallow history */
		if (historyVector[0] != State.$NullState$) {
			shallowEnterSequence_main_region_Choice_and_Payment_Choice_region_Chosed_or_not_r1();
		} else {
			enterSequence_main_region_Choice_and_Payment_Choice_region_Chosed_or_not_r1_No_choice_default();
		}
	}
	
	/* Default react sequence for initial entry  */
	private void react_main_region_Choice_and_Payment_Choice_region__entry_Default() {
		enterSequence_main_region_Choice_and_Payment_Choice_region_Chosed_or_not_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react_main_region_Choice_and_Payment_Payment_region_Payed_or_not_r1__entry_Default() {
		enterSequence_main_region_Choice_and_Payment_Payment_region_Payed_or_not_r1_No_money_default();
	}
	
	/* Default react sequence for shallow history entry History */
	private void react_main_region_Choice_and_Payment_Payment_region_Payed_or_not_r1_History() {
		/* Enter the region with shallow history */
		if (historyVector[1] != State.$NullState$) {
			shallowEnterSequence_main_region_Choice_and_Payment_Payment_region_Payed_or_not_r1();
		} else {
			enterSequence_main_region_Choice_and_Payment_Payment_region_Payed_or_not_r1_No_money_default();
		}
	}
	
	/* Default react sequence for initial entry  */
	private void react_main_region_Choice_and_Payment_Payment_region__entry_Default() {
		enterSequence_main_region_Choice_and_Payment_Payment_region_Payed_or_not_default();
	}
	
	/* Default react sequence for initial entry  */
<<<<<<< HEAD
	private void react_main_region_Step1_r1__entry_Default() {
		enterSequence_main_region_Step1_r1_Water_heat_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react_main_region_Step1_r2__entry_Default() {
		enterSequence_main_region_Step1_r2_Drink_difference_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react_main_region_Step2_r1__entry_Default() {
		enterSequence_main_region_Step2_r1_Cup_Placement_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react_main_region_Step2_r2__entry_Default() {
		enterSequence_main_region_Step2_r2_Drink_difference_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react_main_region_Step3_r1__entry_Default() {
		enterSequence_main_region_Step3_r1_Water_wait_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react_main_region_Step3_r2__entry_Default() {
		enterSequence_main_region_Step3_r2_Sugar_added_default();
	}
	
	/* The reactions of exit default. */
	private void react_main_region_Step2_r1__exit_Default() {
		effect_main_region_Step2_tr0();
	}
	
	/* The reactions of exit default. */
	private void react_main_region_Step2_r2__exit_Default() {
		effect_main_region_Step2_tr0();
=======
	private void react_main_region_Fin_de_la_commande_nettoyage__entry_Default() {
		enterSequence_main_region_Fin_de_la_commande_nettoyage_Nettoyage_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react_main_region_Fin_de_la_commande_fin_de_la_commande_rendu_monnaie__entry_Default() {
		enterSequence_main_region_Fin_de_la_commande_fin_de_la_commande_rendu_monnaie_Rendre_monnaie_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react_main_region_Fin_de_la_commande_R_cup_rer_gobelet__entry_Default() {
		enterSequence_main_region_Fin_de_la_commande_R_cup_rer_gobelet_Gobelet_pret_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react_main_region_Preparation_de_la_boisson_gobelet__entry_Default() {
		enterSequence_main_region_Preparation_de_la_boisson_gobelet_Positionnement_dosette_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react_main_region_Preparation_de_la_boisson_eau__entry_Default() {
		enterSequence_main_region_Preparation_de_la_boisson_eau_Chauffage_default();
>>>>>>> 68d868c1c4efdf8a22dfb9d5b0c54d4297ed849b
	}
	
	private boolean react() {
		return false;
	}
	
	private boolean main_region_Choice_and_Payment_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (((timeEvents[0]) && ((sCInterface.getSelected() && sCInterface.getPayedEnough())))) {
				exitSequence_main_region_Choice_and_Payment();
				sCInterface.raiseDoTransaction();
				
				enterSequence_main_region_Step1_default();
				react();
			} else {
				did_transition = false;
			}
		}
		if (did_transition==false) {
			did_transition = react();
		}
		return did_transition;
	}
	
	private boolean main_region_Choice_and_Payment_Choice_region_Chosed_or_not_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if ((sCInterface.teaButton || (sCInterface.coffeeButton || sCInterface.expressoButton))) {
				exitSequence_main_region_Choice_and_Payment_Choice_region_Chosed_or_not();
				entryAction_main_region_Choice_and_Payment_Choice_region_Chosed_or_not();
				enterSequence_main_region_Choice_and_Payment_Choice_region_Chosed_or_not_r1_Drink_chosed_default();
			} else {
				if (timeEvents[1]) {
					exitSequence_main_region_Choice_and_Payment_Choice_region_Chosed_or_not();
					sCInterface.raiseCancel();
					
					enterSequence_main_region_Choice_and_Payment_Choice_region_Chosed_or_not_default();
				} else {
					if ((sCInterface.insertCoin10 || (sCInterface.insertCoin25 || (sCInterface.insertCoin50 || sCInterface.nFC)))) {
						exitSequence_main_region_Choice_and_Payment_Choice_region_Chosed_or_not();
						entryAction_main_region_Choice_and_Payment_Choice_region_Chosed_or_not();
						react_main_region_Choice_and_Payment_Choice_region_Chosed_or_not_r1_history();
					} else {
						if (sCInterface.cancelButton) {
							exitSequence_main_region_Choice_and_Payment_Choice_region_Chosed_or_not();
							sCInterface.raiseCancel();
							
							entryAction_main_region_Choice_and_Payment_Choice_region_Chosed_or_not();
							enterSequence_main_region_Choice_and_Payment_Choice_region_Chosed_or_not_r1_No_choice_default();
						} else {
							did_transition = false;
						}
					}
				}
			}
		}
		return did_transition;
	}
	
	private boolean main_region_Choice_and_Payment_Choice_region_Chosed_or_not_r1_Drink_chosed_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			did_transition = false;
		}
		if (did_transition==false) {
			did_transition = main_region_Choice_and_Payment_Choice_region_Chosed_or_not_react(try_transition);
		}
		return did_transition;
	}
	
	private boolean main_region_Choice_and_Payment_Choice_region_Chosed_or_not_r1_No_choice_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			did_transition = false;
		}
		if (did_transition==false) {
			did_transition = main_region_Choice_and_Payment_Choice_region_Chosed_or_not_react(try_transition);
		}
		return did_transition;
	}
	
	private boolean main_region_Choice_and_Payment_Payment_region_Payed_or_not_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if ((sCInterface.insertCoin10 || (sCInterface.insertCoin25 || sCInterface.insertCoin50))) {
				exitSequence_main_region_Choice_and_Payment_Payment_region_Payed_or_not();
				entryAction_main_region_Choice_and_Payment_Payment_region_Payed_or_not();
				enterSequence_main_region_Choice_and_Payment_Payment_region_Payed_or_not_r1_Money_inserted_default();
				main_region_Choice_and_Payment_react(false);
			} else {
				if (timeEvents[2]) {
					exitSequence_main_region_Choice_and_Payment_Payment_region_Payed_or_not();
					sCInterface.raiseGiveBackMoney();
					
					enterSequence_main_region_Choice_and_Payment_Payment_region_Payed_or_not_default();
				} else {
					if ((sCInterface.enoughMoneyInserted || sCInterface.nFC)) {
						exitSequence_main_region_Choice_and_Payment_Payment_region_Payed_or_not();
						entryAction_main_region_Choice_and_Payment_Payment_region_Payed_or_not();
						enterSequence_main_region_Choice_and_Payment_Payment_region_Payed_or_not_r1_Enough_money_default();
						main_region_Choice_and_Payment_react(false);
					} else {
						if ((sCInterface.coffeeButton || (sCInterface.teaButton || sCInterface.expressoButton))) {
							exitSequence_main_region_Choice_and_Payment_Payment_region_Payed_or_not();
							entryAction_main_region_Choice_and_Payment_Payment_region_Payed_or_not();
							react_main_region_Choice_and_Payment_Payment_region_Payed_or_not_r1_History();
						} else {
							if (sCInterface.cancelButton) {
								exitSequence_main_region_Choice_and_Payment_Payment_region_Payed_or_not();
								sCInterface.raiseGiveBackMoney();
								
								entryAction_main_region_Choice_and_Payment_Payment_region_Payed_or_not();
								enterSequence_main_region_Choice_and_Payment_Payment_region_Payed_or_not_r1_No_money_default();
								main_region_Choice_and_Payment_react(false);
							} else {
								did_transition = false;
							}
						}
					}
				}
			}
		}
		if (did_transition==false) {
			did_transition = main_region_Choice_and_Payment_react(try_transition);
		}
		return did_transition;
	}
	
	private boolean main_region_Choice_and_Payment_Payment_region_Payed_or_not_r1_No_money_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			did_transition = false;
		}
		if (did_transition==false) {
			did_transition = main_region_Choice_and_Payment_Payment_region_Payed_or_not_react(try_transition);
		}
		return did_transition;
	}
	
	private boolean main_region_Choice_and_Payment_Payment_region_Payed_or_not_r1_Money_inserted_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			did_transition = false;
		}
		if (did_transition==false) {
			did_transition = main_region_Choice_and_Payment_Payment_region_Payed_or_not_react(try_transition);
		}
		return did_transition;
	}
	
	private boolean main_region_Choice_and_Payment_Payment_region_Payed_or_not_r1_Enough_money_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			did_transition = false;
		}
		if (did_transition==false) {
			did_transition = main_region_Choice_and_Payment_Payment_region_Payed_or_not_react(try_transition);
		}
		return did_transition;
	}
	
<<<<<<< HEAD
	private boolean main_region_Step1_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			exitSequence_main_region_Step1();
			sCInterface.raiseEndFirstStep();
			
			enterSequence_main_region_Step2_default();
=======
	private boolean main_region_Fin_de_la_commande_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			exitSequence_main_region_Fin_de_la_commande();
			enterSequence_main_region_Choice_and_Payment_default();
>>>>>>> 68d868c1c4efdf8a22dfb9d5b0c54d4297ed849b
			react();
		}
		if (did_transition==false) {
			did_transition = react();
		}
		return did_transition;
	}
	
<<<<<<< HEAD
	private boolean main_region_Step1_r1_Water_heat_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (sCInterface.endWaterHeat) {
				exitSequence_main_region_Step1_r1_Water_heat();
				enterSequence_main_region_Step1_r1__final__default();
			} else {
				did_transition = false;
			}
=======
	private boolean main_region_Fin_de_la_commande_nettoyage_Nettoyage_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			did_transition = false;
>>>>>>> 68d868c1c4efdf8a22dfb9d5b0c54d4297ed849b
		}
		return did_transition;
	}
	
<<<<<<< HEAD
	private boolean main_region_Step1_r1__final__react(boolean try_transition) {
=======
	private boolean main_region_Fin_de_la_commande_fin_de_la_commande_rendu_monnaie_Rendre_monnaie_react(boolean try_transition) {
>>>>>>> 68d868c1c4efdf8a22dfb9d5b0c54d4297ed849b
		boolean did_transition = try_transition;
		
		if (try_transition) {
			did_transition = false;
		}
		return did_transition;
	}
	
<<<<<<< HEAD
	private boolean main_region_Step1_r2_First_step_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (timeEvents[3]) {
				exitSequence_main_region_Step1_r2_First_step();
				sCInterface.raiseEndFirstStep();
				
				enterSequence_main_region_Step1_r2__final__default();
=======
	private boolean main_region_Fin_de_la_commande_R_cup_rer_gobelet_Gobelet_pret_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (sCInterface.getGobeletTaken()) {
				exitSequence_main_region_Fin_de_la_commande_R_cup_rer_gobelet_Gobelet_pret();
				enterSequence_main_region_Fin_de_la_commande_R_cup_rer_gobelet_Gobelet_r_cup_r__default();
				main_region_Fin_de_la_commande_react(false);
>>>>>>> 68d868c1c4efdf8a22dfb9d5b0c54d4297ed849b
			} else {
				did_transition = false;
			}
		}
		if (did_transition==false) {
<<<<<<< HEAD
			did_transition = main_region_Step1_react(try_transition);
=======
			did_transition = main_region_Fin_de_la_commande_react(try_transition);
		}
		return did_transition;
	}
	
	private boolean main_region_Fin_de_la_commande_R_cup_rer_gobelet_Gobelet_r_cup_r__react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			did_transition = false;
		}
		if (did_transition==false) {
			did_transition = main_region_Fin_de_la_commande_react(try_transition);
>>>>>>> 68d868c1c4efdf8a22dfb9d5b0c54d4297ed849b
		}
		return did_transition;
	}
	
<<<<<<< HEAD
	private boolean main_region_Step1_r2_Drink_difference_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (sCInterface.podPlacement) {
				exitSequence_main_region_Step1_r2_Drink_difference();
				sCInterface.raisePodPlaced();
				
				enterSequence_main_region_Step1_r2_First_step_default();
				main_region_Step1_react(false);
			} else {
				if (sCInterface.seedGrind) {
					exitSequence_main_region_Step1_r2_Drink_difference();
					sCInterface.raiseSeedGrinded();
					
					enterSequence_main_region_Step1_r2_First_step_default();
					main_region_Step1_react(false);
				} else {
					if (sCInterface.bagPlacement) {
						exitSequence_main_region_Step1_r2_Drink_difference();
						sCInterface.raiseBagPlaced();
						
						enterSequence_main_region_Step1_r2_First_step_default();
						main_region_Step1_react(false);
					} else {
						did_transition = false;
					}
				}
			}
		}
		if (did_transition==false) {
			did_transition = main_region_Step1_react(try_transition);
=======
	private boolean main_region_Preparation_de_la_boisson_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (timeEvents[3]) {
				exitSequence_main_region_Preparation_de_la_boisson();
				enterSequence_main_region_Fin_de_la_commande_default();
				react();
			} else {
				did_transition = false;
			}
		}
		if (did_transition==false) {
			did_transition = react();
>>>>>>> 68d868c1c4efdf8a22dfb9d5b0c54d4297ed849b
		}
		return did_transition;
	}
	
<<<<<<< HEAD
	private boolean main_region_Step1_r2__final__react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			did_transition = false;
		}
		if (did_transition==false) {
			did_transition = main_region_Step1_react(try_transition);
=======
	private boolean main_region_Preparation_de_la_boisson_gobelet_Positionnement_dosette_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			exitSequence_main_region_Preparation_de_la_boisson_gobelet_Positionnement_dosette();
			enterSequence_main_region_Preparation_de_la_boisson_gobelet_Positionnement_gobelet_default();
		}
		return did_transition;
	}
	
	private boolean main_region_Preparation_de_la_boisson_gobelet_Positionnement_gobelet_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			exitSequence_main_region_Preparation_de_la_boisson_gobelet_Positionnement_gobelet();
			enterSequence_main_region_Preparation_de_la_boisson_gobelet_Ajout_du_sucre_default();
>>>>>>> 68d868c1c4efdf8a22dfb9d5b0c54d4297ed849b
		}
		return did_transition;
	}
	
<<<<<<< HEAD
	private boolean main_region_Step2_react(boolean try_transition) {
=======
	private boolean main_region_Preparation_de_la_boisson_gobelet_Ajout_du_sucre_react(boolean try_transition) {
>>>>>>> 68d868c1c4efdf8a22dfb9d5b0c54d4297ed849b
		boolean did_transition = try_transition;
		
		if (try_transition) {
			did_transition = false;
		}
		return did_transition;
	}
	
	private boolean main_region_Preparation_de_la_boisson_eau_Chauffage_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (((timeEvents[4]) && (sCInterface.getHotEnough()))) {
				exitSequence_main_region_Preparation_de_la_boisson_eau_Chauffage();
				enterSequence_main_region_Preparation_de_la_boisson_eau_AssezChauff__default();
				main_region_Preparation_de_la_boisson_react(false);
			} else {
				did_transition = false;
			}
		}
		if (did_transition==false) {
			did_transition = main_region_Preparation_de_la_boisson_react(try_transition);
		}
		return did_transition;
	}
	
	private boolean main_region_Preparation_de_la_boisson_eau_AssezChauff__react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (((timeEvents[5]) && (sCInterface.getGobeletOk()))) {
				exitSequence_main_region_Preparation_de_la_boisson_eau_AssezChauff_();
				enterSequence_main_region_Preparation_de_la_boisson_eau_Versement_de_l_eau_default();
				main_region_Preparation_de_la_boisson_react(false);
			} else {
				did_transition = false;
			}
		}
		if (did_transition==false) {
			did_transition = main_region_Preparation_de_la_boisson_react(try_transition);
		}
		return did_transition;
	}
	
	private boolean main_region_Preparation_de_la_boisson_eau_Versement_de_l_eau_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			did_transition = false;
		}
		if (did_transition==false) {
			did_transition = main_region_Preparation_de_la_boisson_react(try_transition);
		}
		return did_transition;
	}
	
	private boolean main_region_End_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (sCInterface.gobeletRecupere) {
				exitSequence_main_region_End();
				enterSequence_main_region_Preparation_de_la_boisson_default();
				react();
			} else {
				did_transition = false;
			}
		}
		if (did_transition==false) {
			did_transition = react();
		}
		return did_transition;
	}
	
	private boolean main_region_Step2_r1_Cup_Placement_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (timeEvents[4]) {
				exitSequence_main_region_Step2_r1_Cup_Placement();
				react_main_region_Step2_r1__exit_Default();
			} else {
				did_transition = false;
			}
		}
		return did_transition;
	}
	
	private boolean main_region_Step2_r2_Drink_difference_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (sCInterface.waitingForWater) {
				exitSequence_main_region_Step2_r2_Drink_difference();
				sCInterface.raiseWaitForWater();
				
				enterSequence_main_region_Step2_r2_Second_step_default();
				main_region_Step2_react(false);
			} else {
				if (sCInterface.seedPacking) {
					exitSequence_main_region_Step2_r2_Drink_difference();
					sCInterface.raisePackSeed();
					
					enterSequence_main_region_Step2_r2_Second_step_default();
					main_region_Step2_react(false);
				} else {
					did_transition = false;
				}
			}
		}
		if (did_transition==false) {
			did_transition = main_region_Step2_react(try_transition);
		}
		return did_transition;
	}
	
	private boolean main_region_Step2_r2_Second_step_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (timeEvents[5]) {
				exitSequence_main_region_Step2_r2_Second_step();
				react_main_region_Step2_r2__exit_Default();
			} else {
				did_transition = false;
			}
		}
		if (did_transition==false) {
			did_transition = main_region_Step2_react(try_transition);
		}
		return did_transition;
	}
	
	private boolean main_region_Step3_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			did_transition = false;
		}
		if (did_transition==false) {
			did_transition = react();
		}
		return did_transition;
	}
	
	private boolean main_region_Step3_r1_Water_wait_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			did_transition = false;
		}
		return did_transition;
	}
	
	private boolean main_region_Step3_r2_Sugar_added_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			did_transition = false;
		}
		if (did_transition==false) {
			did_transition = main_region_Step3_react(try_transition);
		}
		return did_transition;
	}
	
}
